#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".tsx\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo "\nValidating Javascript:\n"

for FILE in $STAGED_FILES
do
  ./node_modules/.bin/eslint "$FILE"

  if [[ "$?" != 0 ]]; then
    echo "\033[41mESLint Failed: $FILE\033[0m"
    PASS=false
  fi
done

./node_modules/.bin/prettier --check $STAGED_FILES
#for FILE in $STAGED_FILES
#do
#  ./node_modules/.bin/prettier --check "$FILE"
#
#  if [[ "$?" != 0 ]]; then
#    echo "\033[41mPrettier Failed: $FILE\033[0m"
#    PASS=false
#  fi
#done

echo "\nJavascript validation completed!\n"

if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
  exit 1
else
  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
