#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".tsx\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo "\nValidating Javascript:\n"

for FILE in $STAGED_FILES
do
  ./node_modules/.bin/eslint "$FILE"

  if [[ "$?" != 0 ]]; then
    echo "\033[41mESLint Failed: $FILE\033[0m"
    PASS=false
  fi
done

./node_modules/.bin/prettier --check $STAGED_FILES

echo "\nValidating Typescript types...\n"

./node_modules/.bin/tsc

if [[ "$?" != 0 ]]; then
  echo "\033[41mTypescript failed\033[0m"
  PASS=false
fi

echo "\nJavascript validation completed!\n"

if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint as tsc but do not. Please fix the ESLint and typescript errors and try again.\n"
  exit 1
else
  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
