platform :android do
  desc "RN Production App"
  lane :distribute do
    gradle(task: 'clean assembleRelease', project_dir: './android', print_command: false, properties: {
      "HAQQ_UPLOAD_STORE_FILE" => ENV["HAQQ_UPLOAD_STORE_FILE"],
      "HAQQ_UPLOAD_STORE_PASSWORD" => ENV["HAQQ_UPLOAD_STORE_PASSWORD"],
      "HAQQ_UPLOAD_KEY_ALIAS" => ENV["HAQQ_UPLOAD_KEY_ALIAS"],
      "HAQQ_UPLOAD_KEY_PASSWORD" => ENV["HAQQ_UPLOAD_KEY_PASSWORD"]
    })

    firebase_app_distribution(
      app: "1:427318688544:android:740c299a1aab9b6f07f545",
      testers: ENV["FIREBASE_TESTERS"],
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      release_notes: "Lots of amazing new features to test out!"
    )
  end
end
