import {I18N} from '@app/i18n';
import {getAppVersion, getBuildNumber} from '@app/services/version';
import {LEDGER_APP, PLATFORM_COMPANY, STRINGS} from '@app/variables/common';

export const ar = {
  [I18N.empty]: '',
  [I18N.numericKeyboard0]: '0',
  [I18N.numericKeyboard1]: '1',
  [I18N.numericKeyboard2]: '2',
  [I18N.numericKeyboard3]: '3',
  [I18N.numericKeyboard4]: '4',
  [I18N.numericKeyboard5]: '5',
  [I18N.numericKeyboard6]: '6',
  [I18N.numericKeyboard7]: '7',
  [I18N.numericKeyboard8]: '8',
  [I18N.numericKeyboard9]: '9',
  [I18N.stakingInfoRewardIsReceived]: 'تم استلام المكافأة',
  [I18N.backupCreateRecoveryPhrase]: 'عبارة الاسترداد',
  [I18N.backupCreateRecoverySaveWords]:
    'اكتب هذه الكلمات أو انسخها بالترتيب الصحيح واحفظها في مكان آمن.',
  [I18N.backupCreateRecoveryWarningMessage]:
    'إذا فقدت عبارة الاسترداد الخاصة بك, فلن تتمكن من الوصول إلى أموالك, حيث لن يتمكن أحد من استعادتها.',
  [I18N.backupCreateRecoveryAgreement]:
    'أدرك أنه إذا فقدت عبارة الاسترداد, فلن أتمكن من استعادة الوصول إلى حسابي',
  [I18N.backupCreateScreenshotWarningTitle]: 'تحذير!',
  [I18N.backupCreateScreenshotWarningSubtitle]:
    'إن التقاط لقطة شاشة لعبارة الاسترداد يزيد من المخاطر الأمنية لحسابك.',
  [I18N.backupCreateVerifyTitle]: 'عبارة الاسترداد',
  [I18N.backupWarningButton]: 'مفهوم',
  [I18N.backupWarningInfoBlock1]:
    'إذا فقدت عبارة الاسترداد الخاصة بك, فلن تتمكن من الوصول إلى أموالك, حيث لن يتمكن أحد من استعادتها.',
  [I18N.backupWarningInfoBlock2]:
    'هذه العبارة هي فرصتك الوحيدة لاستعادة إمكانية الوصول إلى أموالك إذا كان جهازك غير متاح لك.',
  [I18N.backupWarningTitle]: 'معلومات استرداد مهمة',
  [I18N.backupWarningParagraph]:
    'النسخة الاحتياطية عبارة عن عبارة استعادة مكونة من 12 كلمة. من الأفضل كتابة العبارة على الورق وعدم الاحتفاظ بها على الإنترنت.',
  [I18N.ledgerBluetoothAllow]: 'متابعة',
  [I18N.ledgerBluetoothTitleUnknown]: 'السماح باستخدام البلوتوث',
  [I18N.ledgerBluetoothTitleDisabled]: 'لا يمكن الوصول إلى البلوتوث',
  [I18N.ledgerBluetoothDescriptionUnknown]:
    'يستخدم التطبيق البلوتوث للعثور على أجهزة Ledger Nano والاتصال بها والتواصل معها',
  [I18N.ledgerBluetoothDescriptionDisabled]:
    "لا يستطيع التطبيق الوصول إلى البلوتوث الخاص بك. يرجى الانتقال إلى إعدادات هاتفك والسماح للتطبيق باستخدام البلوتوث.بدون هذا, لن نتمكن من العثور على Ledger Nano X' الخاص بك",
  [I18N.transactionLedgerBluetoothDisabled]: 'لا يمكن الوصول إلى البلوتوث',
  [I18N.transactionLedgerBluetoothConfirmation]: `افتح تطبيق ${LEDGER_APP} على دفتر الأستاذ الخاص بك وقم بتأكيد المعاملة عن طريق الضغط على الزرين معًا`,
  [I18N.createAgreementTitle]: 'HAQQ - محفظة DeFi',
  [I18N.createAgreementText]:
    "لا تقوم محفظة HAQQ بتخزين أو نقل أو إرسال أو تحويل أو الاحتفاظ أو التفاعل بأي شكل من الأشكال مع أي من العملات الافتراضية التي قد تستخدمها مع تطبيق محفظة HAQQ. أي تحويل أو معاملة تتم على شبكة (شبكات) HAQQ. لا تستطيع محفظة HAQQ حظر أو تجميد أو السيطرة على عملتك الافتراضية بأي شكل من الأشكال.'",
  [I18N.createAgreementAgree]: 'أوافق',
  [I18N.termsAgreementFirst]: 'بالنقر على "موافقة", فإنك توافق على',
  [I18N.termsOfService]: 'شروط الخدمة',
  [I18N.termsAgreementSecond]: ' و',
  [I18N.termsPrivacyPolicy]: 'سياسة الخصوصية',
  [I18N.restoreAgreementTitle]: 'هل لديك عبارة الاسترداد أو المفتاح الخاص؟',
  [I18N.restoreAgreementText]:
    'عبارة الاسترداد عبارة عن عبارة مكونة من 12 كلمة تلقيتها عند إنشاء الحساب. المفتاح الخاص هو المفتاح الذي قمت بإنشائه في التطبيق',
  [I18N.restoreAgreementAgree]: "'أوافق'",
  [I18N.restorePasswordAttentionTitle]: 'انتباه. قد تخسر كل أموالك!',
  [I18N.restorePasswordAttentionSubtitle]:
    'لا تقم بإعادة تعيين التطبيق إذا لم تكن متأكدًا من أنه يمكنك استعادة حسابك. للاستعادة, ستحتاج إلى عبارة استرداد مكونة من 12 كلمة قمت بإنشائها لحسابك',
  [I18N.restorePasswordReset]: 'إعادة تعيين',
  [I18N.restorePasswordForgot]: 'هل نسيت كلمة المرور؟',
  [I18N.restorePasswordWarning]:
    'للأسف, لا يمكن إعادة تعيين كلمة المرور. حاول الانتظار قليلاً وتذكر كلمة المرور. إذا لم ينجح الأمر, فانقر فوق الزر "إعادة تعيين المحفظة" واستخدم العبارة الاحتياطية لاستعادة المحفظة. إذا لم تكن هناك عبارة احتياطية, فلن تتمكن من استعادة المحفظة',
  [I18N.restorePasswordResetWallet]: 'إعادة تعيين المحفظة',
  [I18N.ledgerAgreementTitle]: 'ربط دفتر الأستاذ الخاص بك',
  [I18N.ledgerAgreementText]:
    'إذا كان لديك Ledger Nano X, فيمكنك توصيله عبر البلوتوث بمحفظة HAQQ. ستتمكن من إدارة الأموال من Ledger باستخدام Islm Wallet,',
  [I18N.ledgerAgreementAgree]: 'اتصال',
  [I18N.ledgerAccountsAdd]: 'إضافة',
  [I18N.ledgerAccountsAdded]: 'تمت الإضافة',
  [I18N.ledgerAccountsWaiting]: 'في انتظار تأكيد الاقتران',
  [I18N.ledgerAccountsConfirm]: 'تأكيد الاقتران في دفتر الأستاذ الخاص بك',
  [I18N.ledgerAccountsLoadMore]: 'تحميل المزيد',
  [I18N.ledgerAccountsLoadInfo]:
    '\'في المرة الأولى, نعرض 5 حسابات فقط من دفتر الأستاذ الخاص بك. إذا كنت تريد رؤية الحسابات الخمسة التالية, فانقر فوق الزر "تحميل المزيد"',
  [I18N.ledgerFinishCongratulations]: 'تهانينا! لقد قمت بإضافة حساب جديد بنجاح',
  [I18N.ledgerScanTitle]: 'البحث عن الأجهزة',
  [I18N.ledgerScanDescription1]: 'يرجى التأكد من أن Ledger Nano X الخاص بك هو',
  [I18N.ledgerScanDescription2]: 'test',
  [I18N.ledgerScanDescription3]: 'تم تمكين البلوتوث',
  [I18N.ledgerScanDescription4]: ' و',
  [I18N.ledgerScanDescription5]: `تم تثبيت تطبيق ${LEDGER_APP} على دفتر الأستاذ الخاص بك`,
  [I18N.ledgerScanDescription6]: 'وفتح',
  [I18N.backupVerifyTitle]: 'التحقق من عبارة الاسترداد',
  [I18N.backupVerifyError]: 'عفوا, خطأ في إحدى الكلمات',
  [I18N.backupVerifyDescription]:
    'يرجى اختيار الرقم الصحيح وفقًا للرقم التسلسلي',
  [I18N.backupVerifyPage1Description]: 'من 1 إلى 12',
  [I18N.backupVerifyPage2Description]: 'من 13 إلى 24',
  [I18N.backupVerifyCheck]: 'التحقق',
  [I18N.modalQRTitle]: 'مسح رمز QR ضوئيًا',
  [I18N.modalQRNoAccessTitle]: 'لا يمكن الوصول إلى الكاميرا',
  [I18N.modalQRNoAccessDescription]:
    'لا يستطيع التطبيق الوصول إلى الكاميرا الخاصة بك. يرجى الانتقال إلى إعدادات هاتفك والسماح للتطبيق باستخدام الكاميرا.وبدون ذلك, لن نتمكن من مسح رمز الاستجابة السريعة ضوئيًا.',
  [I18N.modalQRSendFunds]: 'إرسال أموال من',
  [I18N.modalDetailsQRWarning]:
    'يتم دعم الأصول المتعلقة بـ ISLM فقط على شبكة HAQQ.',
  [I18N.onboardingFinishCreate]: 'تهانينا!\nلقد قمت بإضافة حساب جديد بنجاح',
  [I18N.onboardingFinishRecover]: 'تهانينا!\nلقد نجحت في استرداد الحساب',
  [I18N.onboardingRepeatPinInvalidCode]: 'رمز غير صالح. حاول ثانية',
  [I18N.onboardingRepeatPinRepeat]: 'الرجاء تكرار الرمز السري',
  [I18N.onboardingRepeatPinSecurity]:
    'لدواعي الأمان, ليس لدينا زر "استعادة الدبوس".\n\n',
  [I18N.modalDetailsQRReceive]: 'استلام',
  [I18N.transactionContactEditHeaderTitle]: 'تحرير جهة الاتصال',
  [I18N.transactionSumSendTitle]: 'إرسال',
  [I18N.transactionSumAddressTitle]: 'العنوان',
  [I18N.transactionSelectCryptoTitle]: 'حدد التشفير',
  [I18N.transactionAccountSendFundsTitle]: 'إرسال أموال من',
  [I18N.transactionLedgerConfirmationTitle]: 'تأكيد',
  [I18N.transactionConfirmationPreviewTitle]: 'معاينة',
  [I18N.transactionAddressPlaceholder]: 'العنوان (0x) أو اسم جهة الاتصال',
  [I18N.transactionAddressError]: 'عنوان غير صحيح',
  [I18N.transactionAddressLabel]: 'إرسال إلى',
  [I18N.transactionsEmpty]: 'لا توجد معاملات',
  [I18N.trackActivityTitle]: 'السماح لمحفظة HAQQ بتتبع نشاطك',
  [I18N.trackActivityImprovement]: 'تحسين',
  [I18N.trackActivityImprovementDescription]:
    'هذا سيساعدنا على جمع المزيد من المعلومات حول مشاكل التطبيق',
  [I18N.trackActivityPrivacy]: 'الأمان والخصوصية',
  [I18N.trackActivityPrivacyDescription]:
    'نحن نقوم بتخزين البيانات التي نتلقاها بشكل آمن. جميع البيانات غير مخصصة',
  [I18N.trackActivityContinue]: 'متابعة',
  [I18N.trackActivityNotNow]: 'ليس الآن',
  [I18N.signInTitle]: 'استرداد حسابك',
  [I18N.settingsAccountEditHeaderTitle]: 'تحرير اسم الحساب',
  [I18N.settingsContactEditHeaderTitle]: 'جهة اتصال',
  [I18N.settingsContactEditDeleteContact]: 'حذف جهة الاتصال',
  [I18N.settingsContactEditNamePlaceholder]: 'أدخل اسمًا',
  [I18N.signUpTitle]: 'إنشاء محفظة',
  [I18N.copy]: 'نسخ',
  [I18N.yes]: 'نعم',
  [I18N.no]: 'لا',
  [I18N.name]: 'الاسم',
  [I18N.address]: 'العنوان',
  [I18N.accept]: 'قبول',
  [I18N.cancel]: 'إلغاء',
  [I18N.save]: 'حفظ',
  [I18N.share]: 'مشاركة',
  [I18N.edit]: 'تحرير',
  [I18N.favourite]: 'المفضلة',
  [I18N.recent]: 'الأخيرة',
  [I18N.clear]: 'واضح',
  [I18N.thereNoBookmarks]: 'لا توجد إشارات مرجعية',
  [I18N.thereNoRecentSites]: 'لا توجد مواقع حديثة',
  [I18N.editBookmarksTitle]: 'الإشارات المرجعية',
  [I18N.editBookmarksRemoveAlert]:
    'هل أنت متأكد أنك تريد إزالة المضلع من الإشارات المرجعية؟',
  [I18N.browserSearchHistory]: 'سجل البحث',
  [I18N.continue]: 'استمر',
  [I18N.delete]: 'حذف',
  [I18N.actionSheetDiscard]: 'تجاهل التغييرات',
  [I18N.actionSheetKeepEditing]: 'مواصلة التحرير',
  [I18N.actionSheetMessage]: 'هل أنت متأكد من رغبتك في تجاهل تغييراتك؟',
  [I18N.settingsCurrencyScreen]: 'العملة',
  [I18N.settingsThemeScreen]: 'المظهر',
  [I18N.settingsThemeLight]: 'الضوء',
  [I18N.settingsThemeDark]: 'مظلم',
  [I18N.settingsThemeSystem]: 'النظام',
  [I18N.homeSettingsAbout]: 'حول',
  [I18N.homeSettingsAccounts]: 'إدارة الحسابات',
  [I18N.homeSettingsAddressBook]: 'دفتر العناوين',
  [I18N.homeSettingsCurrency]: 'العملة',
  [I18N.homeSettingsAppearance]: 'المظهر',
  [I18N.homeSettingsWalletConnect]: 'اتصال المحفظة',
  [I18N.homeSettingsSecurity]: 'الأمان',
  [I18N.homeSettingsProviders]: 'مقدمو الخدمات',
  [I18N.homeSettingsFAQ]: 'الأسئلة الشائعة',
  [I18N.homeSettingsTest]: 'اختبار',
  [I18N.homeSettingsDeveloperTools]: 'أدوات المطور',
  [I18N.homeSettingsLanguage]: 'اللغة',
  [I18N.backupNotificationTitle]:
    'قم بعمل نسخة احتياطية لحسابك, وحافظ على أصولك آمنة',
  [I18N.backupNotificationDescription]:
    'إذا كانت عبارة الاسترداد في غير محلها أو تمت سرقتها, فهذا يعادل فقدان محفظتك. إنها الطريقة الوحيدة للوصول إلى محفظتك إذا نسيت كلمة مرور حسابك.',
  [I18N.backupNotificationBackup]: 'النسخ الاحتياطي الآن',
  [I18N.backupNotificationSkip]: 'سأخاطر بذلك',
  [I18N.backupNotificationAlertTitle]: 'هل تريد المتابعة بدون النسخ الاحتياطي؟',
  [I18N.backupNotificationAlertDescription]:
    'إذا فقدت إمكانية الوصول إلى محفظتك, فلن نتمكن من استعادة حسابك إذا لم تقم بعمل نسخة احتياطية',
  [I18N.modalPinTitle]: 'مرحبًا بك في محفظة HAQQ',
  [I18N.notificationCopied]: 'تم النسخ',
  [I18N.notificationAccountDeleted]: 'تم حذف الحساب',
  [I18N.notificationAccountHidden]: 'تم إخفاء الحساب',
  [I18N.notificationPinChanged]: 'تم تغيير رمز PIN بنجاح',
  [I18N.onboardingSetupPinProjectWallet]:
    'حماية محفظتك." يزيد رمز PIN من أمان المحفظة في حالة سرقة هاتفك.',
  [I18N.onboardingSetupPinSet]: 'تعيين رمز التعريف الشخصي المكون من 6 أرقام',
  [I18N.onboardingBiometryEnable]: 'تمكين {{القياسات الحيوية}}',
  [I18N.onboardingBiometrySafeFast]: 'آمن وسريع',
  [I18N.onboardingBiometrySkip]: 'تخطي',
  [I18N.notificationRewardReceived]: 'تم استلام المكافأة',
  [I18N.modalPinForgotCode]: 'نسيت\nالرمز',
  [I18N.pinManyAttempts]: 'محاولات كثيرة جدًا, يرجى الانتظار {{محاولات}}',
  [I18N.homeWallet]: 'الرئيسية',
  [I18N.homeWalletTitle]: 'محافظك',
  [I18N.homeSettings]: 'الإعدادات',
  [I18N.homeSettingsTitle]: 'الإعدادات',
  [I18N.homeBrowserTitle]: 'المتصفح',
  [I18N.homeBrowser]: 'المتصفح',
  [I18N.errorLoadingPage]: 'حدث خطأ أثناء تحميل الصفحة',
  [I18N.errorReason]: 'السبب: {{سبب}}',
  [I18N.browserSearch]: 'بحث',
  [I18N.browserEnterSiteNameOrURL]: 'أدخل اسم الموقع أو عنوان URL',
  [I18N.homeNews]: 'الأخبار',
  [I18N.homeNewsTitle]: 'أخبار',
  [I18N.homeEarn]: 'اكسب',
  [I18N.homeStaking]: 'الستاكينج',
  [I18N.ledgerConnect]: 'الاتصال بدفتر الأستاذ',
  [I18N.keystoneConnect]: 'توصيل حجر الزاوية',
  [I18N.ledgerChooseAccount]: 'اختر حساب',
  [I18N.ledgerVerify]: 'تحقق',
  [I18N.homeStakingEmpty]: 'ضع ISLM الخاص بك في أي مدقق واحصل على ISLM إضافي',
  [I18N.homeStakingUnbounded]: 'غير محدود',
  [I18N.homeEarnTitle]: 'اكسب',
  [I18N.homeStakingTitle]: 'الستاكينغ',
  [I18N.homeGovernance]: 'الحوكمة',
  [I18N.homeGovernanceTitle]: 'الحوكمة',
  [I18N.homeGovernanceTagAll]: 'الكل',
  [I18N.homeGovernanceTagVoting]: 'التصويت',
  [I18N.homeGovernanceTagPassed]: 'ناجح',
  [I18N.homeGovernanceTagRejected]: 'مرفوض',
  [I18N.homeGovernanceVotingCardVoting]: 'التصويت',
  [I18N.homeGovernanceVotingCardDepositPeriod]: 'إيداع',
  [I18N.homeGovernanceVotingCardYouVoted]: 'لقد قمت بالتصويت',
  [I18N.homeGovernanceVotingCardYouDeposited]: 'لقد قمت بالإيداع',
  [I18N.homeGovernanceVotingCardVotingEnd]: 'نهاية التصويت',
  [I18N.homeGovernanceVotingCardVotingStart]: 'بدء التصويت',
  [I18N.homeGovernanceVotingCardDay]: 'اليوم',
  [I18N.homeGovernanceVotingCardHour]: 'ساعة',
  [I18N.homeGovernanceVotingCardMin]: 'الحد الأدنى',
  [I18N.homeGovernanceVotingCardPassed]: 'تم النجاح',
  [I18N.homeGovernanceVotingCardRejected]: 'مرفوض',
  [I18N.homeGovernanceDescription]: 'التصويت للتغييرات في الشبكة',
  [I18N.headerPlaceholderSearch]: 'بحث',
  [I18N.homeStakingStaked]: 'رهينة',
  [I18N.homeStakingRewards]: 'المكافآت',
  [I18N.settingsProvidersTitle]: 'مقدمو الخدمات',
  [I18N.settingsProvidersTitleRight]: 'إضافة',
  [I18N.settingsProviderEditHeaderTitle]: 'المزود',
  [I18N.settingsProviderEditName]: 'الاسم',
  [I18N.settingsProviderEditNamePlaceholder]: 'اسم الموفر',
  [I18N.settingsProviderEditNameHint]:
    'يمكنك إدخال أي اسم يناسبك. \nمثال: شبكة HAQQ',
  [I18N.settingsProviderEditEthEndpoint]: 'EVM RPC',
  [I18N.settingsProviderEditEthEndpointPlaceholder]: 'URL',
  [I18N.settingsProviderEditEthEndpointHint]:
    'نقطة نهاية JSON-RPC للتفاعل مع EVM\nمثال: https://rpc.eth.haqq.network/',
  [I18N.settingsProviderEditExplorer]: 'مستكشف EVM',
  [I18N.settingsProviderEditExplorerPlaceholder]: 'URL',
  [I18N.settingsProviderEditExplorerHint]:
    'عنوان URL للمستكشف لمعاملات الشيكات\nمثال: https://explorer.haqq.network/',
  [I18N.settingsProviderEditCosmosEndpoint]: 'Cosmos RPC',
  [I18N.settingsProviderEditCosmosEndpointPlaceholder]: 'URL',
  [I18N.settingsProviderEditCosmosEndpointHint]:
    'نقطة نهاية REST للتفاعل مع وحدات الكون الأصلية\nمثال: https://rpc.cosmos.haqq.network/',
  [I18N.settingsProviderEditCosmosChainId]: 'معرف السلسلة',
  [I18N.settingsProviderEditCosmosChainIdPlaceholder]:
    '{المعرف}_{EIP155}-{الإصدار}',
  [I18N.settingsProviderEditCosmosChainIdHint]: 'مثال: haqq_11235-1',
  [I18N.settingsProviderEditDeleteProvider]: 'حذف الموفر',
  [I18N.settingsTestDelegate]: 'مندوب',
  [I18N.settingsTestReward]: 'المكافأة: {{مكافأة}}',
  [I18N.settingsTestStaked]: 'حصان: {{حصان}}',
  [I18N.settingsTestUnbounded]: 'غير محدود: {{غير محدود}}',
  [I18N.settingsTestUndelegate]: 'إلغاء التفويض',
  [I18N.settingsProviderEditUseProvider]: 'استخدم هذا الموفر',
  [I18N.signupStoreWalletCreatingAccount]: 'إنشاء حسابك',
  [I18N.signupStoreWalletAccountNumber]: 'الحساب رقم {{رقم}}',
  [I18N.signinRestoreWalletPasteClipboard]: 'لصق من الحافظة',
  [I18N.signinRestoreWalletPhraseOrKey]: 'عبارة الاسترداد أو المفتاح الخاص',
  [I18N.signinRestoreWalletRecovery]: 'الاسترداد',
  [I18N.signinRestoreWalletTextFieldError]: 'عنوان غير صحيح',
  [I18N.signinRestoreWalletTextFieldLabel]: 'عبارة احتياطية',
  [I18N.signinRestoreWalletTextFieldPlaceholder]:
    'اكتب عبارة الاسترداد أو الصقها',
  [I18N.signinStoreWalletText]: 'جاري استرداد الحساب',
  [I18N.signinStoreWalletAccountNumber]: 'الحساب رقم {{رقم}}',
  [I18N.keystoneWalletAccountNumber]: `{{deviceName}}${STRINGS.NBSP}#{{walletCount}}`,
  [I18N.keystoneUnknownError]: 'خطأ غير معروف\n{{خطأ}}',
  [I18N.keystoneWalletSyncPathError]:
    'سيدعم Keystone فقط مزامنة العناوين العشرة الأولى لمسار اشتقاق Ledger Live.',
  [I18N.keystoneWalletEnterDeviceNameTitle]: 'إنشاء اسم الجهاز',
  [I18N.keystoneWalletEnterDeviceNameMessage]:
    'أدخل اسم الجهاز لـ Keystone الجديد',
  [I18N.settingsAccountRemoveTitle]:
    'انتباه. قد تخسر كل أموالك! هل انت متأكد انك تريد حذف حسابك؟',
  [I18N.settingsAccountRemoveMessage]:
    'لا تحذف الحساب إذا لم تكن متأكدًا من أنه يمكنك استعادته. للاستعادة, ستحتاج إلى 12 كلمة قمت بإنشائها لحسابك',
  [I18N.settingsAccountRemoveConfirm]: 'حذف',
  [I18N.settingsAccountRemoveReject]: 'إلغاء',
  [I18N.settingsAccountDetailHeaderTitle]: 'تفاصيل الحساب',
  [I18N.settingsAccountDetailRenameTitle]: 'إعادة تسمية الحساب',
  [I18N.settingsAccountDetailRenameSubtitle]: 'تغيير اسم عرض الحساب',
  [I18N.settingsAccountDetailChangeStyleTitle]: 'تغيير النمط',
  [I18N.settingsAccountDetailChangeStyleSubtitle]: 'تغيير صورة الحساب',
  [I18N.settingsAccountDetailHideSubtitle]: 'سوف تكون مخفية من القائمة العامة',
  [I18N.settingsAccountDetailHideTitle]: 'إخفاء الحساب',
  [I18N.settingsAccountDetailViewRecoveryPhraseSubtitle]: 'تغيير صورة الحساب',
  [I18N.settingsViewRecoveryPhraseTitle]: 'عرض عبارة الاسترداد',
  [I18N.settingsAccountDetailViewRecoveryPhraseTitle]: 'عرض عبارة الاسترداد',
  [I18N.settingsContactEditDelete]: 'حذف',
  [I18N.settingsContactEditSure]:
    'هل أنت متأكد أنك تريد حذف جهة الاتصال المحددة؟',
  [I18N.settingsAddressBookLabel]: 'العنوان',
  [I18N.settingsAddressBookPlaceholder]: 'البحث أو إضافة جهة اتصال',
  [I18N.settingsAddressBookTitle]: 'جهات الاتصال الخاصة بي',
  [I18N.settingsAddressBookAdd]: 'إضافة جهة اتصال',
  [I18N.settingsAddressBookAlertTitle]: 'حذف جهة الاتصال',
  [I18N.settingsAddressBookAlertDesc]:
    'هل أنت متأكد أنك تريد حذف جهة الاتصال المحددة؟',
  [I18N.settingsAddressBookAlertBtnFirst]: 'إلغاء',
  [I18N.settingsAddressBookAlertBtnSecond]: 'حذف',
  [I18N.settingsSecurityPinConfirm]: 'تأكيد',
  [I18N.settingsSecurityPinEnter]: 'أدخل',
  [I18N.settingsSecurityPinNotMatched]: 'رقم التعريف الشخصي غير متطابق',
  [I18N.settingsSecurityPinRepeat]: 'الرجاء تكرار الرمز السري',
  [I18N.settingsSecurityPinSet]: 'تعيين رمز التعريف الشخصي المكون من 6 أرقام',
  [I18N.settingsSecurityBiometry]: 'استخدم {{القياسات الحيوية}} لفتح التطبيق',
  [I18N.settingsSecurityChangePin]: 'تغيير رقم التعريف الشخصي',
  [I18N.settingsSecurityEnterPin]: 'أدخل رقم التعريف الشخصي الجديد',
  [I18N.settingsSecurityWalletPin]: 'أدخل رقم التعريف الشخصي لمحفظة HAQQ',
  [I18N.settingsSecurity]: 'الأمان',
  [I18N.sent]: 'مرسل',
  [I18N.transactionSendTitle]: 'تم الإرسال',
  [I18N.transactionReceiveTitle]: 'تم الاستلام',
  [I18N.transactionContractTitle]: 'تفاعل العقد',
  [I18N.transactionContractNamePrefix]: 'الاسم: {{القيمة}}',
  [I18N.transactionContractDefaultName]: 'عقد شبكة HAQQ',
  [I18N.transactionPositiveAmountText]: '+ {{قيمة}}',
  [I18N.transactionNegativeAmountText]: '- {{قيمة}}',
  [I18N.transactionWidgetReceiveTitle]: 'تم استلام {{القيمة}}',
  [I18N.transactionWidgetSpendTitle]: 'إنفاق {{قيمة}}',
  [I18N.transactionWidgetTitle]: 'المعاملات',
  [I18N.transactionWidgetShortTitle]: 'المعاملات الأخيرة',
  [I18N.stakingInfoDelegationNoAvailableWallets]:
    'لا توجد محافظ متاحة للتفويض.',
  [I18N.stakingInfoUnDelegationNoAvailableWallets]:
    'لا توجد محافظ متاحة لإلغاء التفويض.',
  [I18N.stakingValidators]: 'قائمة أدوات التحقق من الصحة',
  [I18N.stakingValidatorsRowPower]: 'الطاقة: {{الطاقة}}',
  [I18N.stakingValidatorsRowStaked]: 'Staked: {{staked}}',
  [I18N.stakingValidatorsRowReward]: 'المكافأة: {{مكافأة}}',
  [I18N.stakingValidatorsRowWithdrawal]: 'السحب قيد المعالجة',
  [I18N.stakingValidatorsStaked]: 'Staked',
  [I18N.stakingValidatorsUnStaked]: 'Unstaked',
  [I18N.stakingInfo]: 'معلومات المدقق',
  [I18N.selectAccount]: 'اختر حساب',
  [I18N.stakingInfoAddress]: 'العنوان',
  [I18N.stakingInfoDetail]: 'التفاصيل',
  [I18N.stakingInfoVotingPower]: 'قوة التصويت',
  [I18N.stakingInfoCommission]: 'عمولة',
  [I18N.stakingInfoWebsite]: 'موقع ويب',
  [I18N.stakingInfoGetReward]: 'احصل على المكافأة',
  [I18N.stakingInfoDelegate]: 'مندوب',
  [I18N.stakingInfoUnDelegate]: 'إلغاء التفويض',
  [I18N.stakingInfoCommissionCurrent]: 'الحالي',
  [I18N.stakingInfoCommissionMax]: 'الحد الأقصى',
  [I18N.stakingInfoCommissionMaxChange]: 'الحد الأقصى للتغيير',
  [I18N.stakingInfoInactive]:
    'عندما تكون أداة التحقق غير نشطة, لن تتمكن من الحصول على مكافأة.',
  [I18N.StakingInfoUnDelegationDays]: ' (بقي {{days}} يوم)',
  [I18N.StakingInfoUnDelegationDay]: ' ({{day}} يوم متبقي)',
  [I18N.validatorStatusActive]: 'نشط',
  [I18N.validatorStatusInactive]: 'غير نشط',
  [I18N.validatorStatusJailed]: 'مسجون',
  [I18N.validatorInfoReward]: 'مكافأة',
  [I18N.validatorInfoStaked]: 'رهينة',
  [I18N.validatorInfoUndelegateInProcess]: 'إلغاء التفويض قيد المعالجة',
  [I18N.validatorInfoShowOther]: 'إظهار الآخرين',
  [I18N.validatorInfoHide]: 'إخفاء',
  [I18N.voteAbstain]: 'امتناع',
  [I18N.voteVeto]: 'الفيتو',
  [I18N.voteRegistered]: 'تم تسجيل التصويت',
  [I18N.voteNotRegistered]: 'خطأ. ولم يتم إرسال التصويت',
  [I18N.stakingDelegateFormTitle]: 'مندوب',
  [I18N.stakingDelegateFormStakeTo]: 'المشاركة في',
  [I18N.stakingDelegateFormJailedAttention]:
    'عندما تكون أداة التحقق غير نشطة, لن تتمكن من الحصول على مكافأة.',
  [I18N.stakingDelegateFormCommission]: 'العمولة',
  [I18N.stakingDelegateFormPreview]: 'معاينة',
  [I18N.stakingDelegatePreviewTitle]: 'معاينة',
  [I18N.stakingDelegatePreviewTotalAmount]: 'المبلغ الإجمالي',
  [I18N.stakingDelegatePreviewStakeTo]: 'Stake to',
  [I18N.stakingDelegatePreviewCommission]: 'العمولة',
  [I18N.stakingDelegatePreviewAmount]: 'المبلغ',
  [I18N.stakingDelegatePreviewNetworkFee]: 'رسوم الشبكة',
  [I18N.stakingDelegatePreviewDelegate]: 'مندوب',
  [I18N.stakingDelegateAccountTitle]: 'الحساب',
  [I18N.stakingDelegateFinishTitle]: 'اكتمل التفويض',
  [I18N.stakingDelegateFinishTotalAmount]: 'المبلغ الإجمالي',
  [I18N.stakingDelegateFinishDone]: 'تم',
  [I18N.stakingUnDelegateFormTitle]: 'إلغاء التفويض',
  [I18N.stakingUnDelegateFormCommission]: 'العمولة',
  [I18N.stakingUnDelegateFormPreview]: 'معاينة',
  [I18N.stakingUnDelegatePreviewTitle]: 'معاينة',

  [I18N.stakingUnDelegatePreviewTotalAmount]: 'المبلغ الإجمالي',
  [I18N.stakingUnDelegatePreviewWithdrawFrom]: 'الانسحاب من',
  [I18N.stakingUnDelegatePreviewCommission]: 'العمولة',
  [I18N.stakingUnDelegatePreviewAmount]: 'المبلغ',
  [I18N.stakingUnDelegatePreviewNetworkFee]: 'رسوم الشبكة',
  [I18N.stakingUnDelegatePreviewButton]: 'إلغاء التفويض',
  [I18N.stakingUnDelegatePreviewAttention]:
    'انتباه! إذا كنت تريد في المستقبل إلغاء تفويض الأموال المرهونة, فسوف يستغرق الأمر {{time}}',
  [I18N.stakingUnDelegatePreviewJailedAttention]:
    'عندما تكون أداة التحقق غير نشطة, لن تتمكن من الحصول على مكافأة.',
  [I18N.stakingUnDelegateFinishTitle]: 'بدأ إلغاء التفويض',
  [I18N.stakingUnDelegateFinishTotalAmount]: 'المبلغ الإجمالي',
  [I18N.stakingUnDelegateFinishDone]: 'تم',

  [I18N.stakingHomeValidators]: 'Validators',
  [I18N.stakingHomeGetRewards]: 'احصل على المكافآت',
  [I18N.stakingUnDelegateAccountTitle]: 'الحساب',
  [I18N.stakingUnDelegateSumWarning]: 'سيتم إلغاء تفويض الأموال خلال {{time}}',
  [I18N.sumBlockMax]: 'الحد الأقصى',
  [I18N.sumBlockAvailable]: 'متاح',
  [I18N.sumAmountNotEnough]: 'ليس لديك ما يكفي من ISLM لدفع الرسوم',
  [I18N.sumAmountTooLow]: 'يجب أن يكون مساويًا أو أكبر من {{amount}}',
  [I18N.popupNotificationTitle]: 'تشغيل الإشعارات',
  [I18N.popupNotificationDescription]:
    'يمكننا إعلامك عند حدوث شيء مهم, مثل: تم إرسال المعاملة بنجاح. وصلت الأموال إلى المحفظة. لقد اكتشفنا أي مخاطر تتعلق بأمان حسابك',
  [I18N.popupNotificationTurnOn]: 'تشغيل الإشعارات',
  [I18N.popupNotificationNotNow]: 'ليس الآن',
  [I18N.popupProposalVoteTitle]: 'اختر ما تريد التصويت له',
  [I18N.popupProposalVoteDescription]: 'يمكنك تغيير تصويتك أثناء إجراء التصويت',
  [I18N.proposalVoteResults]: 'نتائج التصويت',
  [I18N.proposalVoteSendingVote]: 'نحن نرسل صوتك...',
  [I18N.proposalYouVoted]: 'لقد قمت بالتصويت',
  [I18N.proposalAccountTitle]: 'التصويت من',
  [I18N.proposalDepositFinishDone]: 'تم',
  [I18N.proposalDepositFinishTotalAmount]: 'المبلغ الإجمالي',
  [I18N.proposalDepositFormTitle]: 'إيداع',
  [I18N.proposalDepositPreviewTitle]: 'معاينة',
  [I18N.proposalDepositDepositFrom]: 'الإيداع من',
  [I18N.proposalDepositTitle]: 'اكتمل الإيداع',
  [I18N.proposalDepositTotalAmount]: 'المبلغ الإجمالي',
  [I18N.welcomeTitle]: 'لا يوجد حساب متصل',
  [I18N.welcomeDescription]: 'يمكنك إنشاء حساب جديد أو ربط أي حساب موجود',
  [I18N.welcomeCreateWallet]: 'إنشاء حساب',
  [I18N.welcomeLedgerWallet]: 'اتصال',
  [I18N.settingsAboutTitle]: 'حول التطبيق',
  [I18N.settingsAboutVisit]: 'قم بزيارة islamiccoin.net',
  [I18N.settingsAboutDocuments]: 'المستندات القانونية',
  [I18N.settingsAboutTerms]: 'الشروط والأحكام',
  [I18N.settingsAboutPrivacyPolicy]: 'سياسة الخصوصية',
  [I18N.settingsAboutSocials]: 'شبكاتنا الاجتماعية',
  [I18N.settingsAboutDiscord]: 'الخلاف',
  [I18N.settingsAboutTwitter]: 'تويتر',
  [I18N.settingsAboutRights]: `الإصدار ${getAppVersion()} (${getBuildNumber()})`,
  [I18N.welcomeRestoreWallet]: 'لدي حساب بالفعل',
  [I18N.welcomeSocialWallet]: 'تسجيل الدخول عبر وسائل التواصل الاجتماعي',
  [I18N.backupFinishCongratulation]: 'تهانينا!',
  [I18N.settingsAccountStyleChoseColor]: 'اختر نمط اللون',
  [I18N.settingsAccountStyleGenerate]: 'إنشاء',
  [I18N.settingsAccountStyleUseStyle]: 'استخدم هذا النمط',
  [I18N.settingsAccountStyleAlreadyUsed]: 'تم استخدام هذا النمط',
  [I18N.settingsAccountStyleFlat]: 'مسطح',
  [I18N.settingsAccountStyleGradient]: 'تدرج',
  [I18N.settingsAccountStyleCircle]: 'دائرة',
  [I18N.settingsAccountStyleRhombus]: 'المعين',
  [I18N.backupFinishSuccess]: 'لقد قمت بحماية حسابك بنجاح.',
  [I18N.backupFinishFinish]: 'متابعة',
  [I18N.proposalTitle]: 'اقتراح',
  [I18N.transactionSumSend]: 'إرسال إلى',
  [I18N.transactionSumPreview]: 'معاينة',
  [I18N.transactions]: 'المعاملات',
  [I18N.to]: 'إلى {{عنوان}}',
  [I18N.transactionSendTo]: 'إلى {{عنوان}}',
  [I18N.transactionConfirmationSend]: 'إرسال',
  [I18N.transactionConfirmationAmount]: '{{amount}} ISLM',
  [I18N.transactionConfirmationHAQQ]: 'HAQQ blockchain',
  [I18N.transactionConfirmationHQ]: '(HQ)',
  [I18N.transactionConfirmationIslamicCoin]: 'عملة إسلامية',
  [I18N.transactionConfirmationISLM]: '(ISLM)',
  [I18N.transactionConfirmationSendTo]: 'إرسال إلى',
  [I18N.transactionConfirmationTotalAmount]: 'المبلغ الإجمالي',
  [I18N.transactionConfirmationSum]: '{{sum}} ISLM',
  [I18N.transactionFinishSendingComplete]: 'اكتملت المعاملة!',
  [I18N.transactionFinishEditContact]: 'تحرير جهة الاتصال',
  [I18N.transactionFinishAddContact]: 'إضافة جهة اتصال',
  [I18N.transactionFinishHash]: 'المستكشف',
  [I18N.transactionFinishDone]: 'تم',
  [I18N.transactionFinishContactAdded]: 'تمت إضافة جهة الاتصال',
  [I18N.transactionFinishContactUpdated]: 'تم تحديث جهة الاتصال',
  [I18N.transactionFinishContactMessage]: 'العنوان:\n{{عنوان}}',
  [I18N.transactionFinishContactMessagePlaceholder]: 'اسم جهة الاتصال',
  [I18N.settingsAccountNoWallet]: 'لا توجد محافظ',
  [I18N.proposalInfo]: 'معلومات',
  [I18N.proposalDescription]: 'الوصف',
  [I18N.proposalType]: 'النوع',
  [I18N.proposalTotalDeposit]: 'إجمالي الإيداع',
  [I18N.proposalDate]: 'التاريخ',
  [I18N.proposalCreatedAt]: 'تم الإنشاء في (توقيت جرينتش)',
  [I18N.proposalVoteStart]: 'بدء التصويت (بتوقيت جرينتش)',
  [I18N.proposalDepositEnd]: 'نهاية الإيداع (بتوقيت جرينتش)',
  [I18N.proposalVoteEnd]: 'انتهاء التصويت (بتوقيت جرينتش)',
  [I18N.proposalChanges]: 'تغييرات المعلمات',
  [I18N.proposalPlan]: 'خطة الترقية',
  [I18N.proposalTypeParameterChangeProposal]: 'تغيير المعلمة',
  [I18N.proposalTypeSoftwareUpgradeProposal]: 'ترقية البرنامج',
  [I18N.proposalTypeClientUpdateProposal]: 'تحديث العميل',
  [I18N.proposalTypeUnknown]: 'غير معروف',
  [I18N.proposalDepositAttention]:
    'إذا لم يجمع الاقتراح العدد المطلوب من الودائع في وقت معين, فسيتم رفضه',
  [I18N.proposalDeposit]: 'إيداع',
  [I18N.proposalNotEnough]: 'الحالي {{percent}}% (الحد الأدنى 51%). ',
  [I18N.proposalNotEnoughDescription]:
    'إذا لم يحصل الاقتراح على العدد المطلوب من الأصوات في مدة معينة فسيتم رفضه',
  [I18N.proposalNoVoting]: 'لا يوجد مقترحات {{votingCategory}}',
  [I18N.ledgerStoreWalletSaving]: 'جاري حفظ الحساب',
  [I18N.keystoneStoreWalletSaving]: 'جاري حفظ الحساب',
  [I18N.ledgerVerifyAddress]:
    'تحقق من العنوان {{address}} الموجود على جهاز Ledger Nano X بالضغط على الزرين معًا',
  [I18N.finishProceed]: 'متابعة',
  [I18N.ledgerFinishTitle]: 'تهانينا!\nلقد قمت بإضافة حساب جديد بنجاح',
  [I18N.transactionDetailTotalAmount]: 'المبلغ الإجمالي',
  [I18N.transactionDetailViewOnBlock]: 'عرض في مستكشف الكتل',
  [I18N.transactionDetailSent]: 'تم الإرسال',
  [I18N.transactionDetailRecive]: 'استلام',
  [I18N.transactionDetailSentTo]: 'تم الإرسال إلى',
  [I18N.transactionDetailReciveFrom]: 'تم الاستلام من',
  [I18N.transactionDetailDate]: 'التاريخ',
  [I18N.transactionDetailNetwork]: 'الشبكة',
  [I18N.transactionDetailAmount]: 'المبلغ',
  [I18N.transactionDetailNetworkFee]: 'رسوم الشبكة',
  [I18N.transactionDetailCryptocurrency]: 'عملة مشفرة',
  [I18N.transactionDetailTransactionType]: 'نوع المعاملة',
  [I18N.transactionDetailContractName]: 'اسم العقد',
  [I18N.transactionDetailTransactionTypeDescription]:
    'عملية التفاعل مع العقد. أنت تدفع فقط ثمن الغاز',
  [I18N.walletCreateAddAccount]: 'إضافة حسابات',
  [I18N.walletCreateImportAndCreate]: 'استيراد وإنشاء حسابات جديدة',
  [I18N.walletCreateNew]: 'إنشاء جديد',
  [I18N.walletCreateConnect]: 'اتصال',
  [I18N.walletCreateImport]: 'استيراد',
  [I18N.walletCardSend]: 'إرسال',
  [I18N.walletCardWithoutBackup]: 'بدون نسخة احتياطية',
  [I18N.walletCardWithoutProtection]: 'لا توجد نسخة احتياطية',
  [I18N.walletCardPartiallyProtection]: 'جزئيًا',
  [I18N.walletCardFullProtection]: 'محمي',
  [I18N.walletCardImported]: 'مستورد',
  [I18N.restoreWalletScreenTitle]: 'استرداد حسابك',
  [I18N.noInternetPopupTitle]: 'لا يوجد إنترنت',
  [I18N.noInternetPopupDescription]:
    'تأكد من أنك متصل بشبكة Wi-Fi أو شبكة خلوية',
  [I18N.errorAccountAddedTitle]: 'تمت إضافة هذا الحساب بالفعل',
  [I18N.errorAccountAddedClose]: 'إغلاق',
  [I18N.errorCreateAccountPopupTitle]: 'فشل في إنشاء حساب',
  [I18N.errorCreateAccountPopupDescription]: 'الرجاء إعادة المحاولة لاحقًا',
  [I18N.errorCreateAccountPopupClose]: 'إغلاق',
  [I18N.networkFee]: 'رسوم الشبكة: {{القيمة}}',
  [I18N.qrModalSendFunds]: 'إرسال أموال من',
  [I18N.qrModalInvalidCode]: 'رمز غير صالح',
  [I18N.ledgerAttentionTitle]: `افتح تطبيق ${LEDGER_APP} على دفتر الأستاذ الخاص بك وقم بتأكيد المعاملة عن طريق الضغط على الزرين معًا`,
  [I18N.ledgerAttentionClose]: 'إغلاق',
  [I18N.ledgerLockedTitle]: 'تشغيل وفتح دفتر الأستاذ',
  [I18N.ledgerLockedDescription]:
    'لا يمكننا الحصول على معلومات من دفتر الأستاذ الخاص بك. ربما تم إيقاف تشغيله أو حظره',
  [I18N.ledgerLockedClose]: 'إغلاق',
  [I18N.ledgerNoAppTitle]: `تثبيت تطبيق ${LEDGER_APP} على Ledger`,
  [I18N.ledgerNoAppDescription]: `بدون هذا التطبيق, لن نتمكن من توصيل دفتر الأستاذ الخاص بك. انتقل إلى تطبيق Ledger Live وقم بتثبيت تطبيق ${LEDGER_APP}`,
  [I18N.ledgerNoAppRetry]: 'تحقق',
  [I18N.ledgerNoAppClose]: 'إغلاق',
  [I18N.transactionErrorTitle]: 'فشلت المعاملة',
  [I18N.bluetoothPoweredOffTitle]: 'تشغيل البلوتوث',
  [I18N.bluetoothPoweredOffDescription]:
    'للاتصال بدفتر الأستاذ, تحتاج إلى تشغيل البلوتوث على هاتفك',
  [I18N.bluetoothPoweredOffClose]: 'إغلاق',
  [I18N.bluetoothUnauthorizedTitle]: 'لا يمكن الوصول إلى البلوتوث',
  [I18N.bluetoothUnauthorizedDescription]:
    "لا يستطيع التطبيق الوصول إلى البلوتوث الخاص بك. يرجى الانتقال إلى إعدادات هاتفك والسماح للتطبيق باستخدام البلوتوث.بدون هذا, لن نتمكن من العثور على Ledger Nano X' الخاص بك",
  [I18N.bluetoothUnauthorizedClose]: 'إغلاق',
  [I18N.transactionFailed]: 'حدث خطأ ما\nالرمز: {{id}}',
  [I18N.errorText]: 'حدث خطأ ما (انقر لإظهار التفاصيل)',
  [I18N.errorCode]: 'الكود: {{id}}',
  [I18N.walletConnectTitle]: 'WalletConnect',
  [I18N.walletConnectSignTitle]: 'عملية التوقيع',
  [I18N.pinCodeWrongPin]: 'يتبقى {{محاولات}} محاولات خاطئة',
  [I18N.walletConnectApplicationListTitle]: 'حساب {{حساب}} متصل',
  [I18N.walletConnectWalletListTitle]: 'WalletConnect',
  [I18N.walletConnectApprovalTitle]: 'الاتصال بـ {{name}}',
  [I18N.walletConnectApprovalDescription]: 'islamiccoin.net',
  [I18N.walletRowVariant2Title]: 'الحساب',
  [I18N.walletConnectApprovalInfoBlockTitle]: 'من خلال الاتصال فإنك تسمح بـ:\n',
  [I18N.walletConnectDisconnect]: 'قطع الاتصال',
  [I18N.walletConnectSignTransactionForSignature]: 'معاملة للتوقيع',
  [I18N.walletConnectSignForm]: 'من',
  [I18N.walletConnectSignSendTo]: 'إرسال إلى',
  [I18N.walletConnectApprovalExpired]: 'تاريخ انتهاء الصلاحية',
  [I18N.walletConnectSignTotalAmount]: 'المبلغ الإجمالي',
  [I18N.walletConnectSignApproveButton]: 'تسجيل',
  [I18N.walletConnectApprovalConnected]: 'متصل',
  [I18N.walletConnectSignRejectButton]: 'رفض',
  [I18N.walletConnectSignSignMessage]: 'وقع هذه الرسالة',
  [I18N.walletConnectSignMessage]: 'رسالة',
  [I18N.walletConnectApprovalInfoBlockDescription]:
    '• عرض رصيدك ونشاطك\n• طلب الموافقة على المعاملات',
  [I18N.walletCardConnectedApps]: '{{count}} اتصال',
  [I18N.settingsTestShareCopied]: 'تم نسخ المشاركة',
  [I18N.sssFinishCongratulations]: 'تهانينا! لقد قمت بإضافة حساب جديد بنجاح',
  [I18N.sssConnect]: 'تسجيل الدخول عبر وسائل التواصل الاجتماعي',
  [I18N.sssStoreWalletSaving]: 'جاري حفظ الحساب',
  [I18N.sssQuestionWrongPassword]: 'كلمة مرور خاطئة',
  [I18N.backupSssNotificationBackupGoogleDrive]:
    'إنشاء نسخة احتياطية على Google Drive',
  [I18N.backupSssNotificationBackupICloud]: 'إنشاء نسخة احتياطية على iCloud',
  [I18N.backupSssNotificationCheck]:
    'التحقق من النسخة الاحتياطية على محرك جوجل',
  [I18N.backupSssSuggestionConnect]: 'اتصال',
  [I18N.backupSssSuggestionCancel]: 'الاتصال لاحقًا',
  [I18N.locationUnauthorizedTitle]: 'لا يمكن الوصول إلى الموقع الدقيق',
  [I18N.socialButtonContinueWith]: 'استمر مع {{provider}}',
  [I18N.sssLoginLater]: 'قم بتسجيل الدخول عبر وسائل التواصل الاجتماعي لاحقًا',
  [I18N.sssLoginLaterDescription]:
    'سيساعد هذا في الحفاظ على إمكانية الوصول إلى الحساب في حالة فقده. يمكنك دائمًا تمكين هذه الميزة في إعدادات حسابك',
  [I18N.sssLoginLaterTitle]:
    'هل أنت متأكد من أنك لا تريد تمكين تسجيل الدخول عبر وسائل التواصل الاجتماعي؟',
  [I18N.sssNetworkWeb3AuthDescription]:
    'لتمكين تسجيل الدخول الاجتماعي, تجمع محفظة HAQQ البريد الإلكتروني للمستخدم ولكنها تخزن فقط تجزئة البريد الإلكتروني.',
  [I18N.signinNetworkDisclaimer]:
    'لتمكين تسجيل الدخول الاجتماعي, تجمع محفظة HAQQ البريد الإلكتروني للمستخدم ولكنها تخزن فقط تجزئة البريد الإلكتروني.',
  [I18N.locationUnauthorizedDescription]:
    'تتطلب محفظة HAQQ الحصول على إذن\nالموقع الدقيق لإقران جهازكe من خلال البلوتوث.\n\nلا تستطيع محفظة HAQQ الوصول إلى معلومات موقعك.',
  [I18N.sssMigrateAgreementAgree]: 'مفهوم',
  [I18N.sssMigrateRewriteRewrite]: 'استبدال',
  [I18N.sssMigrateRewriteCancel]: 'تغيير تسجيل الدخول الاجتماعي',
  [I18N.sssMigrateRewriteTitle]:
    'لديك بالفعل حساب على {{provider}} تسجيل الدخول {{email}}',
  [I18N.sssMigrateRewriteDescription]:
    'يمكنك اختيار تسجيل دخول اجتماعي آخر لحسابك أو استبداله.',
  [I18N.sssMigrateRewriteWarning]:
    'في حالة الاستبدال, سيتم فقدان جميع بيانات الحساب',
  [I18N.settingsAccountDetailPhrase]: 'العبارة',
  [I18N.settingsAccountDetailSocial]: 'اجتماعي',
  [I18N.settingsAccountDetailCreateBackupPhrase]: 'إنشاء عبارة احتياطية',
  [I18N.settingsAccountDetailConnectSocialLogin]:
    'اتصال تسجيل الدخول الاجتماعي',
  [I18N.settingsAccountDetailRecoveryWarning]:
    'هذا الحساب غير محمي. قم بإنشاء عبارة استرداد له أو قم بتوصيله بشبكة اجتماعية',
  [I18N.settingsAccountDetailRecoveryPhraseWarning]:
    'لم يتم إنشاء عبارة احتياطية للحساب. يمكن أن يكون بمثابة إجراء إضافي للحماية في حالة فقدان الوصول إلى الحساب',
  [I18N.settingsAccountDetailRecoverySocialWarning]:
    'إذا فقدت إمكانية الوصول إلى حسابك, فيمكنك دائمًا استعادته باستخدام شبكتك الاجتماعية',
  [I18N.walletProtectionTitle]: 'حماية حسابك',
  [I18N.walletProtectionPhrase]: 'العبارة',
  [I18N.walletProtectionSocial]: 'اجتماعي',
  [I18N.walletProtectionRecoveryPhrase]: 'عبارة الاسترداد',
  [I18N.walletProtectionRecoveryPhraseDescription]:
    'بمساعدة عبارة مكونة من 12 كلمة, يمكنك استعادة حسابك',
  [I18N.walletProtectionSocialLinkConnect]: 'الحساب الاجتماعي',
  [I18N.walletProtectionSocialLinkConnectDescription]:
    'سيتم ربط حساب محفظة HAQQ الخاص بك بتسجيل الدخول الاجتماعي الذي اخترته. يمكنك استخدامه لاستعادة حسابك',
  [I18N.walletProtectionDescription]:
    'نحن نقدم طريقتين لحماية حسابك. يمكنك الجمع بين كليهما',
  [I18N.signupNetworkExistsRestore]: 'استعادة الحساب',
  [I18N.signupNetworkExistsRewrite]: 'استبدال',
  [I18N.signinNetworksSkip]: 'العبارة أو المفتاح الخاص',
  [I18N.signinPinTitle]: 'أدخل رمز PIN الخاص بك من تطبيق HAQQ',
  [I18N.signinOldPinTitle]: 'أدخل رقم التعريف الشخصي القديم لمحفظة HAQQ',
  [I18N.customNetwork]: 'شبكة مخصصة',
  [I18N.signNotExitsCreateAccount]: 'إنشاء حساب',
  [I18N.signNotExitsChoiceAnother]: 'اختر آخر',
  [I18N.signNotRecoveryTitle]: 'للأسف لم نعثر على ملف الاسترداد المحفوظ',
  [I18N.signNotRecoveryDescription]:
    'للاستعادة, يمكنك إدخال رمز PIN القديم أو اختيار تسجيل دخول اجتماعي مختلف',
  [I18N.signNotRecoveryOldPin]: 'أدخل رمز PIN القديم',
  [I18N.signNotRecoveryChangeSocial]: 'تغيير تسجيل الدخول الاجتماعي',
  [I18N.sssMigrateRewriteAlertTitle]: 'هل أنت متأكد من أنك تريد استبدال حسابك؟',
  [I18N.sssMigrateRewriteAlertDescription]:
    'سيتم فقدان جميع البيانات الموجودة في الحساب ولن تكون قابلة للاسترداد',
  [I18N.sssMigrateFinishText]: 'تهانينا! لقد نجحت في ربط شبكتك الاجتماعية.',
  [I18N.sssMigrateAgrementTitle]: 'معلومات مهمة',
  [I18N.sssMigrateAgrementWarning1]:
    'من خلال تمكين الحساب الاجتماعي, سيتم ربط حساب محفظتك بتسجيل الدخول الاجتماعي المحدد. إذا فقدت الوصول إلى تسجيل الدخول الاجتماعي الخاص بك, فيمكنك استعادة حساب محفظتك باستخدام العبارة الاحتياطية, بشرط أن تكون قد قمت بحفظ واحدة من قبل.\n\nللحصول على وظيفة الحساب الاجتماعي, فنحن نجمع عناوين البريد الإلكتروني للمستخدمين ولكن نخزن فقط الإصدارات المجزأة منها.',
  [I18N.sssMigrateAgrementWarning2]:
    'يُرجى ملاحظة أن استعادة حساب المحفظة باستخدام حساب اجتماعي لا يعمل إلا مع تطبيق المحفظة الخاص بنا.',
  [I18N.backupSssSuggestionTitle]:
    'اجعل حسابك أكثر أمانًا - اربطه بالشبكة الاجتماعية',
  [I18N.backupSssSuggestionDescription]:
    'إذا فقدت إمكانية الوصول إلى حسابك, فيمكنك دائمًا استعادته باستخدام شبكتك الاجتماعية',
  [I18N.signNotExitsDescription]:
    'لا توجد حسابات مرتبطة في شبكتنا لتسجيل الدخول الاجتماعي الذي اخترته. قم بإنشاء حساب جديد بناءً على تسجيل الدخول الاجتماعي هذا أو اختر تسجيل دخول اجتماعي آخر',
  [I18N.signNotExitsTitle]:
    'لم نجد الحساب متصلاً بتسجيل الدخول {{provider}} {{email}}',
  [I18N.signupNetworkExitsTitle]:
    'لديك بالفعل حساب على {{provider}} تسجيل الدخول {{email}}',
  [I18N.signupNetworkExitsTitleWithoutEmail]:
    'لديك بالفعل حساب على {{provider}} تسجيل الدخول',
  [I18N.signupNetworkExitsDescription1]: 'يمكنك استعادة حسابك أو استبداله.',
  [I18N.signupNetworkExitsDescription2]:
    'في حالة الاستبدال, سيتم فقدان جميع بيانات الحساب',
  [I18N.signupNetworkExitsAlertTitle]:
    'هل أنت متأكد من أنك تريد استبدال حسابك؟',
  [I18N.signupNetworkExitsAlertDescription]:
    'سيتم فقدان جميع البيانات الموجودة في الحساب ولن تكون قابلة للاسترداد',
  [I18N.networks]: 'الشبكات',
  [I18N.modalRewardErrorTitle]: 'البعضلقد حدث خطأ ما',
  [I18N.modalRewardErrorDescription]:
    'نحن نمنح ISLM لإنشاء الحساب الأول. المجمع اليومي للمكافآت هو 100 ISLM. لسوء الحظ, تمت المطالبة بجميع مكافآت اليوم, لكن حاول مرة أخرى غدًا!',
  [I18N.modalRewardErrorClose]: 'إغلاق',
  [I18N.rewardCreatingFirstAccount]: 'مكافأة إنشاء الحساب الأول',
  [I18N.rewardBannerClaim]: 'المطالبة بالمكافأة',
  [I18N.amountISLM]: '{{amount}} ISLM',
  [I18N.amountAISLM]: '{{amount}} aISLM',
  [I18N.browserActionMenuProviders]: 'مقدمو الخدمات',
  [I18N.browserActionMenuHome]: 'الصفحة الرئيسية',
  [I18N.browserActionMenuAddToBookmarks]: 'إضافة إلى الإشارات المرجعية',
  [I18N.browserActionMenuRemoveFromBookmarks]: 'إزالة من\nالإشارات المرجعية',
  [I18N.browserActionMenuRefresh]: 'تحديث',
  [I18N.browserActionMenuCopyLink]: 'انسخ الرابط',
  [I18N.browserActionMenuShare]: 'مشاركة',
  [I18N.browserActionMenuDisconnect]: 'قطع الاتصال',
  [I18N.browserToastAddedToBookmarks]: 'تمت الإضافة إلى الإشارات المرجعية',
  [I18N.browserToastRemoveFromBookmarks]: 'إزالة من الإشارات المرجعية',
  [I18N.browserToastLinkCopied]: 'تم نسخ الرابط',
  [I18N.claimOnMainnetTitle]: 'تم استلام الأموال بنجاح على حسابك في Mainnet',
  [I18N.claimOnMainnetDescription]:
    'سوف تكون قادرا على رؤية الأموال المستلمة عن طريق الذهاب إلى الشبكة الرئيسية',
  [I18N.claimOnMainnetChange]: 'انتقل إلى MainNet',
  [I18N.claimOnMainnetStay]: 'ابق على {{شبكة}}',
  [I18N.newsTitle]: 'أخبار',
  [I18N.popupNotificationNewsTitle]: 'اشترك في أخبار IslamCoin',
  [I18N.popupNotificationNewsDescription]:
    'احصل على آخر الأخبار والتحديثات حول العملة الإسلامية ومحفظة HAQQ',
  [I18N.popupNotificationNewsSubscribe]: 'تشغيل إشعارات الأخبار',
  [I18N.popupNotificationNewsNotNow]: 'ليس الآن',
  [I18N.homeSettingsNotification]: 'إشعار',
  [I18N.settingsNotification]: 'إشعار',
  [I18N.newsPushNotification]: 'إشعارات النشرة الإخبارية',
  [I18N.newsPushNotificationsDescription]:
    'احصل على آخر الأخبار والتحديثات حول العملة الإسلامية ومحفظة HAQQ',
  [I18N.rafflePushNotification]: 'إشعارات السحب',
  [I18N.rafflePushNotificationsDescription]:
    'سنخبرك ببدء السحوبات الجديدة وفي حالة الفوز',
  [I18N.transactionPushNotification]: 'إشعارات الدفع للمعاملات',
  [I18N.transactionPushNotificationsDescription]:
    'احصل على إشعارات بشأن عمليات الإيداع والسحب والمعاملات الناجحة',
  [I18N.weDontHaveNotificationPermission]: 'ليس لدينا إذن لإرسال إشعارات إليك',
  [I18N.weDontHaveNotificationPermissionDescription]:
    'للسماح لمحفظة HAQQ بإرسال الإشعارات, يرجى الانتقال إلى إعدادات الهاتف ومنح الإذن',
  [I18N.goToPhoneSettings]: 'انتقل إلى إعدادات الهاتف',
  [I18N.walletConnectPairError]: 'بروتوكول الترحيل غير مدعوم',
  [I18N.walletConnectPairPending]: 'قد يستغرق الاتصال بعض الوقت',
  [I18N.walletConnectNotSupported]: 'WalletConnect v1 غير مدعوم',
  [I18N.walletConnectPairInitError]: 'لم تتم تهيئة WalletConnect',
  [I18N.walletConnectPairAlreadyExists]: 'الجلسة موجودة بالفعل',
  [I18N.backupNotificationNewsAlertTitle]: 'هل تريد المتابعة بدون اشتراك؟',
  [I18N.backupNotificationNewsAlertDescription]:
    'إذا كنت ترغب في الاشتراك في الأخبار في وقت لاحق, يمكنك القيام بذلك في قسم إعدادات الإشعارات.',
  [I18N.later]: 'لاحقًا',
  [I18N.raffleDetailsPreviousRaffle]: 'السحب السابق',
  [I18N.raffleDetailsHaveTickets]: 'لديك: {{tickets}} تذاكر',
  [I18N.raffleDetailsHaveTicket]: 'لديك: تذكرة {{tickets}}',
  [I18N.raffleDetailsPreviousRaffleDetails]:
    'جائزة {{islm}} ISLM (تم الفوز بـ {{tickets}} تذكرة)',
  [I18N.earnWelcomeRaffleTitle]: 'يانصيب مرحبًا',
  [I18N.earnMonthlyRaffleTitle]: 'السحب الشهري',
  [I18N.rafflePrize]: 'الجائزة:',
  [I18N.rafflePrizePool]: 'مجموعة الجوائز:',
  [I18N.earnStaking]: 'الستاكينغ',
  [I18N.earnRewards]: 'المكافآت',
  [I18N.earnRaffles]: 'رافلز',
  [I18N.earnParticipate]: 'مشاركة',
  [I18N.earnGetRewards]: 'الحصول على مكافآت',
  [I18N.earnGetTicket]: 'احصل على تذكرة',
  [I18N.earnShowResult]: 'إظهار النتيجة',
  [I18N.earnRafflesResultCount]: '{{count}} لديه نتيجة',
  [I18N.earnRafflesDescription]: 'شارك في السحوبات واحصل على الجوائز',
  [I18N.earnStakingDescription]:
    'استثمر ISLM الخاص بك في أي مدقق واحصل على ISLM إضافي',
  [I18N.timerDay]: 'يوم',
  [I18N.timerHour]: 'ساعة',
  [I18N.timerMin]: 'الحد الأدنى',
  [I18N.timerSec]: 'ثانية',
  [I18N.raffleTicketRecieved]: 'لقد حصلت على مكافأتك بنجاح',
  [I18N.earnTicketRecieved]: 'تم استلام التذكرة',
  [I18N.earnTicketAlreadyRecieved]: 'تم استلام التذكرة بالفعل',
  [I18N.raffleDetailsTimerFinishTitle]: 'انتهى السحب',
  [I18N.raffleDetailsTimerProgressTitle]: 'سينتهي السحب خلال',
  [I18N.raffleRewardСongratulations]: 'تهانينا!',
  [I18N.raffleRewardUnderstood]: 'مفهوم',
  [I18N.raffleRewardPrize]: 'جائزة {{islm}} ISLM',
  [I18N.raffleRewardWonTickets]:
    '{{winner_tickets}} من إجمالي {{total_tickets}} تذكرة فازت',
  [I18N.raffleDetailsPrizeByTicketDescription]:
    'السعر بواسطة ticket: {{islm}} ISLM. يتم إجراء السحب مرة واحدة في الشهر. يمكن لكل مشارك الحصول على عدة تذاكر. للحصول على تذكرة, اضغط على زر "الحصول على تذكرة", ولن تتوفر تذكرة أخرى إلا بعد 24 ساعة',
  [I18N.sliderCaptchaDragText]: 'اسحب شريط التمرير',
  [I18N.sliderCaptchaTitle]: 'اسحب شريط التمرير ليناسب اللغز',
  [I18N.sliderCaptchaErrorToast]: 'غير صحيح. حاول مرة اخرى',
  [I18N.sliderCaptchaSuccessToast]: 'تم حل اللغز خلال {{sec}} ثانية',
  [I18N.sliderCaptchaRefresh]: 'تحديث',
  [I18N.sliderCaptchaReportProblem]: 'الإبلاغ عن مشكلة',
  [I18N.sortByAdding]: 'بالإضافة',
  [I18N.sortByName]: 'بالاسم',
  [I18N.nftCollectionPreviewItemsCount]: '{{count}} عنصر',
  [I18N.nftCollectionDetailsTitle]: 'مجموعة NFT',
  [I18N.nftItemDetailsTitle]: 'NFT الخاص بك',
  [I18N.trimmedTextReadMore]: 'اقرأ المزيد',
  [I18N.trimmedTextShowLess]: 'إظهار أقل',
  [I18N.nftDetailsDescription]: 'الوصف',
  [I18N.nftDetailsLastSalePrice]: 'آخر سعر بيع',
  [I18N.nftDetailsAttributes]: 'السمات',
  [I18N.nftDetailsSend]: 'إرسال',
  [I18N.nftDetailsTokenId]: 'Token ID',
  [I18N.nftDetailsYourItems]: 'العناصر الخاصة بك',
  [I18N.transactionNftFinishSendingComplete]: 'اكتمل الإرسال',
  [I18N.domainBlockedTitle]: 'النطاق محظور',
  [I18N.domainBlockedDescription1]: 'المجال',
  [I18N.domainBlockedDescription2]: ' غير مسموح بهذه العملية.',
  [I18N.homeFeedTransactionTabTitle]: 'المعاملات',
  [I18N.accountInfoTransactionTabTitle]: 'المعاملات',
  [I18N.homeFeedNftTabTitle]: 'NFTs',
  [I18N.accountInfoNftTabTitle]: 'NFTs',
  [I18N.accountInfoTokensTabTitle]: 'الرموز المميزة',
  [I18N.homeFeedTokensTabTitle]: 'الرموز المميزة',
  [I18N.homeEarnEmptyRaffleTitle]: 'سوف يكون رافلز هنا قريبًا',
  [I18N.homeEarnEmptyRaffleDescription]:
    'قريبا ستتمكن من المشاركة في السحوبات والحصول على الجوائز',
  [I18N.transactionMyAccounts]: 'حساباتي',
  [I18N.transactionMyContacts]: 'جهات الاتصال الخاصة بي',
  [I18N.jailbreakTitle]: 'لا يمكن استخدام المحفظة على جهاز مخترق',
  [I18N.jailbreakDescription1]:
    'وفقًا لسياستنا الأمنية, لا نسمح باستخدام التطبيق على الأجهزة المخترقة. يعد ذلك ضروريًا للحفاظ على سلامة أموال المستخدمين',
  [I18N.jailbreakDescription2]:
    'نوصي بتحديث جهازك إلى البرنامج الثابت الأصلي الذي توفره الشركة المصنعة لجهازك',
  [I18N.nftViewerNoNFTs]: 'لا يوجد NFTs',
  [I18N.ourNewsTitle]: 'أخبارنا',
  [I18N.homeNewsOurNews]: 'أخبارنا',
  [I18N.homeNewsViewAll]: 'عرض الكل',
  [I18N.homeNewsCryptoNews]: 'أخبار العملات المشفرة',
  [I18N.onboardingTrackingUserActivityTitle]:
    'ساعدنا على التحسين: سنقوم بتحسين الميزات التي تستخدمها فعليًا',
  [I18N.onboardingTrackingUserActivityHint1Title]: 'تحسين',
  [I18N.onboardingTrackingUserActivityHint1Description]:
    'هذا سيساعدنا على جمع المزيد من المعلومات حول مشاكل التطبيق',
  [I18N.onboardingTrackingUserActivityHint2Title]: 'الأمان والخصوصية',
  [I18N.onboardingTrackingUserActivityHint2Description]:
    'نحن نقوم بتخزين البيانات التي نتلقاها بشكل آمن. "جميع البيانات غير مخصصة',
  [I18N.onboardingTrackingUserActivityContinue]: 'متابعة',
  [I18N.onboardingTrackingUserActivityNotNow]: 'ليس الآن',
  [I18N.raffleAgreementTitle]: 'اتفاقية ToC',
  [I18N.raffleAgreementDescription]:
    'للانضمام إلى السحب, يجب عليك الموافقة على',
  [I18N.raffleAgreementDescriptionLink]: 'الشروط والأحكام',
  [I18N.raffleAgreementAgree]: 'متابعة',
  [I18N.raffleAgreementClose]: 'إلغاء',
  [I18N.newUpdateTitle]: 'التحديث متاح',
  [I18N.newUpdateDescription]: 'يتوفر تحديث لمحفظة حق. هل ترغب في تحديث؟',
  [I18N.newUpdateCancel]: 'ليس الآن',
  [I18N.newUpdateAccept]: 'تحديث',
  [I18N.walletCardLocked]: 'مقفل: {{count}}',
  [I18N.lockedTokensLocked]: 'مقفل: {{count}}',
  [I18N.lockedTokensAvailable]: 'متاح: {{count}}',
  [I18N.totalAvailable]: 'الإجمالي: {{count}}',
  [I18N.lockedTokensTotalValue]: 'القيمة الإجمالية',
  [I18N.earnHint]: `${PLATFORM_COMPANY} ليس راعيًا لأي عروض ترويجية أو جوائز مذكورة في هذا التطبيق`,
  [I18N.raffleAgreementDescriptionPlatform]: `${PLATFORM_COMPANY} ليس راعيًا لأي عروض ترويجية أو جوائز مذكورة في هذا الطلب.`,
  [I18N.lockedTokensInfoTitle]: 'ماذا يعني "مقفل',
  [I18N.lockedTokensInfoDescription]:
    'الرموز المقفلة هي مجموع الرموز المميزة الخاصة بك - الرموز المميزة والرموز المميزة التي قمت بتثبيتها, بما في ذلك الرموز المميزة الموجودة في فترة عدم الإيداع. \n\nالرموز المميزة هي الرموز المميزة الخاصة بك ولكن لا يمكنك نقلها إلى مستخدمين آخرين أو استخدامها لدفع ثمن الغاز, ولكن يمكنك تفويض المدققين - حصة لتحسين موثوقية شبكة HAQQ وتحقيق الربح. يتم فتح الرموز المميزة وفقًا للجدول الزمني',
  [I18N.totalValueScreenTitle]: 'المعاملات',
  [I18N.totalValueAccount]: 'إجمالي الرصيد',
  [I18N.modalDontHaveFeeError]: 'ليس لديك ما يكفي من ISLM لدفع الرسوم',
  [I18N.modalDontHaveFeeClose]: 'إغلاق',
  [I18N.notEnoughGasTitle]: 'الغاز غير كافٍ',
  [I18N.notEnoughGasDescription]:
    'في الوقت الحالي, تتطلب المعاملة **{{gasLimit}}**, ولكن **ليس لديك سوى {{currentAmount}}** في حسابك.',
  [I18N.notEnoughGasDescription1]: 'حاليًا, معاملة',
  [I18N.notEnoughGasDescription2]: 'يتطلب {{gasLimit}}',
  [I18N.notEnoughGasDescription3]: ', لكن',
  [I18N.notEnoughGasDescription4]: 'لديك فقط {{currentAmount}}',
  [I18N.notEnoughGasDescription5]: 'على حسابك.',
  [I18N.browserActionMenuClose]: 'إغلاق',
  [I18N.splashDescription]: '🌙 صبر...\nمحفظتك تستيقظ',
  [I18N.blockRequestErrorTitle]: 'حدث خطأ ما',
  [I18N.blockRequestOk]: 'حسنًا',
  [I18N.cloudVerificationTitle]: 'محاولة الوصول إلى {{القيمة}}',
  [I18N.cloudVerificationDescription]: 'سيستغرق الأمر بضع ثوانٍ',
  [I18N.cloudProblemsTitle]: 'لم نتمكن من الوصول إلى {{القيمة}}',
  [I18N.cloudProblemsDescription]:
    'لم نتمكن من الاتصال بـ {{value}} الخاص بك حيث يتم تخزين ملف النسخ الاحتياطي لحسابك. يرجى التأكد من أن {{value}} الخاصة بك تعمل بشكل صحيح أو قم باستعادة حسابك باستخدام العبارة التذكيرية الخاصة بك.',
  [I18N.cloudProblemsActionButton]: 'تحقق من الوصول إلى {{قيمة}}',
  [I18N.cloudProblemsSecondaryButton]: 'الاستعادة باستخدام العبارة التذكيرية',
  [I18N.chooseAccountBasicTab]: 'أساسي',
  [I18N.chooseAccountLedgerTab]: 'دفتر الأستاذ',
  [I18N.chooseAccountLoadInfo]:
    'في المرة الأولى, نعرض أول 5 حسابات فقط. إذا كنت تريد رؤية الحسابات الخمسة التالية, فانقر فوق الزر "تحميل المزيد',
  [I18N.chooseAccountAddOneAccountText]: 'أضف حساب {{قيمة}}',
  [I18N.chooseAccountAddManyAccountsText]: 'أضف حسابات {{قيمة}}',
  [I18N.pinAttempts]: 'دبوس خاطئ {{قيمة}} يسار',
  [I18N.signContratAttention]:
    'لم تتم الموافقة على هذا العقد الذكي من قبل فريق IslamCoin. توقيع العقد هو حسب تقديرك الخاص',
  [I18N.dynamicLinkDetactedTitle]: 'تم اكتشاف DynamicLink',
  [I18N.dynamicLinkDetactedDescription]: 'هذا الموقع مفتوح \n{{url}}',
  [I18N.dynamicLinkDetactedIgnore]: 'تجاهل',
  [I18N.dynamicLinkDetactedAllow]: 'السماح',
  [I18N.lockedTokensVested]: 'مُخوَّل: {{count}}',
  [I18N.lockedTokensVestedAvailableIn]: '(سيكون متاحًا في: {{value}})',
  [I18N.lockedTokensStaked]: 'محصّن: {{count}}',
  [I18N.estimatingGas]: 'تقدير...',
  [I18N.transactionInfoContractInteraction]: 'تفاعل العقد',
  [I18N.transactionInfoSendingFunds]: 'إرسال الأموال',
  [I18N.transactionInfoTypeOperation]: 'نوع العملية',
  [I18N.transactionInfoCryptocurrency]: 'عملة مشفرة',
  [I18N.transactionInfoNetwork]: 'الشبكة',
  [I18N.transactionInfoAmount]: 'المبلغ',
  [I18N.transactionInfoNetworkFee]: 'رسوم الشبكة',
  [I18N.transactionInfoMemo]: 'مذكرة',
  [I18N.transactionInforHideRawOperationInfo]: 'إخفاء معلومات العملية الأولية',
  [I18N.transactionInforShowRawOperationInfo]: 'إظهار معلومات العملية الأولية',
  [I18N.developerModeAttentionEnable]: 'تمكين',
  [I18N.developerModeAttentionCancel]: 'إلغاء',
  [I18N.developerModeAttentionTitle]: 'وضع المطور',
  [I18N.developerModeAttentionDescription]:
    'انتباه!!! في هذا الوضع, سيتم إعادة تعيين قيود المتصفح وسيتم توسيع وظائف التطبيق قليلاً. الوضع نشط فقط في شبكة الاختبار.',
  [I18N.unknownError]: 'خطأ غير معروف',
  [I18N.unrecognizedDataFormat]: 'تنسيق بيانات غير معروف. حاول مرة اخرى.',
  [I18N.qrPermissionRequest]: 'طلب إذن QR',
  [I18N.qrPermissionRequestDescription]:
    'هل تريد السماح لموقع الويب هذا {{url}} باستخدام ماسح QR الضوئي؟',
  [I18N.transactionStatusSuccess]: 'نجاح',
  [I18N.transactionStatusFailed]: 'فشل',
  [I18N.transactionStatusInProgress]: 'قيد التقدم',
  [I18N.plusOtherTokens]: '+ {{value}} رموز مميزة أخرى',
  [I18N.plusOtherToken]: '+ {{value}} رمز مميز آخر',
  [I18N.jsonRpcErrorInvalidParams]: 'معلمات غير صالحة',
  [I18N.jsonRpcErrorInvalidProvider]: 'المحفظة غير محددة',
  [I18N.jsonRpcErrorInvalidWallet]: 'موفر المحفظة غير محدد',
  [I18N.tokensZeroBalance]: 'رصيد صفر',
  [I18N.tokensLowBalance]: 'رصيد منخفض',
  [I18N.noTokens]: 'لا توجد رموز مميزة',
  [I18N.tokensSorting]: 'فرز الرموز المميزة',
  [I18N.tokensSortingByAmount]: 'حسب المبلغ',
  [I18N.tokensSortingByAvailable]: 'حسب المتاح',
  [I18N.tokensWidgetTitle]: 'الرموز المميزة',
  [I18N.browserGeolocationPermissionPromptTitle]:
    'يريد موقع الويب هذا استخدام موقعك الحالي.',
  [I18N.browserGeolocationPermissionPromptMessage]:
    ' سيستخدم "{{ hostname }}" موقعك الدقيق.ستتم مشاركة موقعك الدقيق مع هذا الموقع لأن تطبيق "Haqq Wallet" يمكنه الوصول إليه.يرجى ملاحظة: "محفظة حق" لا تقوم بتخزين بيانات موقعك ولن تشاركها مع الموقع إلا بعد الحصول على موافقتك',
  [I18N.browserPermissionPromptAllow]: 'السماح',
  [I18N.browserPermissionPromptAllowOnce]: 'السماح مرة واحدة',
  [I18N.browserPermissionPromptDeny]: 'رفض',
  [I18N.browserSecurityAllow]: 'دائمًا',
  [I18N.browserSecurityAllowOnce]: 'اسأل في المرة القادمة',
  [I18N.browserSecurityDeny]: 'أحدث',
  [I18N.browserGeolocationPermissioUseLocationMessage]:
    '"{{hostname}}" يطلب موقعك الحالي.',
  [I18N.nftWidgetTitle]: 'NFT',
  [I18N.nftWidgetItems]: '{{count}} عنصر',
  [I18N.copyAddress]: 'نسخ العنوان',
  [I18N.copyBech32Address]: 'انسخ عنوان bech32',
  [I18N.evmTitle]: 'EVM',
  [I18N.bech32Title]: 'Bech32',
  [I18N.browserPrivacyTitle]: 'الخصوصية',
  [I18N.browserPrivacy]: 'الخصوصية',
  [I18N.sortValidatorTitle]: 'بواسطة {{sortTitle}}',
  [I18N.transactionCrypto]: 'تشفير',
  [I18N.viewDetailsTitle]: 'عرض التفاصيل',
  [I18N.yourAppVersion]: 'الإصدار الخاص بك: {{version}}',
  [I18N.remoteAppVersion]: 'الإصدار المتاح: {{الإصدار}}',
  [I18N.showInactive]: 'إظهار غير نشط',
  [I18N.sortAsc]: 'a-z',
  [I18N.sortDesc]: 'z-a',
  [I18N.sortValidatorOptionRandom]: 'عشوائي',
  [I18N.sortValidatorOptionName]: 'الاسم ({{مفتاح}})',
  [I18N.sortValidatorOptionPower]: 'الطاقة ({{مفتاح}})',
  [I18N.sortValidatorOptionCommission]: 'العمولة ({{مفتاح}})',
  [I18N.signSharesNotFoundTitle]: 'للأسف لم نعثر على ملف الاسترداد المحفوظ',
  [I18N.signSharesNotFoundDescription]:
    'للأسف, لم نتمكن من العثور على ملف النسخة الاحتياطية في وحدة التخزين السحابية الخاصة بك أو على هاتفك. يرجى التأكد من وجود ملف النسخة الاحتياطية ومحاولة العملية مرة أخرى أو استعادة حسابك من عبارة الاسترداد',
  [I18N.signSharesNotFoundPrimaryButton]: 'التحقق مرة أخرى',
  [I18N.signSharesNotFoundSecondaryButton]:
    'الاستعادة باستخدام العبارة التذكيرية',
  [I18N.cloudShareNotFoundTitle]:
    'لم نتمكن من العثور على ملف النسخ الاحتياطي الخاص بك في التخزين السحابي',
  [I18N.cloudShareNotFoundDescription]:
    'من الممكن أن يكون الملف قد تم حذفه من وحدة التخزين السحابية لديك أو أن هناك مشكلات في المزامنة. نوصي بحفظ ملف النسخة الاحتياطية مرة أخرى',
  [I18N.cloudShareNotFoundPrimaryButton]:
    'الحفظ في مساحة التخزين السحابية الخاصة بك',
  [I18N.cloudShareNotFoundSecondaryButton]: 'تخطي',
  [I18N.invalidQrCodeSync]:
    'رمز الاستجابة السريعة غير صالح. يرجى مسح رمز الاستجابة السريعة للمزامنة الخاص بمحفظة الأجهزة.',
  [I18N.invalidQrCodeSign]:
    'رمز الاستجابة السريعة غير صالح. يرجى التحقق من أجهزتك وإعادة المحاولة.',
  [I18N.unknownQrCode]: 'رمز QR غير صالح. الرجاء اعادة المحاولة.',
  [I18N.keystoneScannerScanning]: 'جارٍ المسح...',
  [I18N.welcomeConnectHardwareWallet]: 'محفظة توصيل الأجهزة',
  [I18N.deviceSelectTitle]: 'اختر نوع محفظة الأجهزة',
  [I18N.deviceSelectDescription]:
    'ستكون قادرًا على إدارة الأموال من Ledger أو Keystone باستخدام محفظة HAQQ',
  [I18N.deviceSelectKeystoneTitle]: 'كيستون',
  [I18N.deviceSelectKeystoneDescription]:
    'امسح رمز الاستجابة السريعة ضوئيًا باستخدام الكاميرا لربط محفظة HAQQ بجهاز Keystone موجود',
  [I18N.deviceSelectLedgerTitle]: 'دفتر الأستاذ',
  [I18N.deviceSelectLedgerDescription]:
    'قم بتوصيل محفظة HAQQ الخاصة بك بجهاز Ledger موجود عبر البلوتوث',
  [I18N.keystoneConnectionStepsTitle]: 'خطوات اتصال Keystone',
  [I18N.keystoneConnectionStepNumber]: 'الخطوة {{idx}}',
  [I18N.keystoneConnectionStepTutorial]: 'عرض البرنامج التعليمي التفصيلي',
  [I18N.keystoneConnectionStepSync]: 'مزامنة كيستون',
  [I18N.keystoneConnectionStepDescription1]:
    'اضغط عى "Software Wallet" في الركن الأيسر السفلي من جهاز Keystone.',
  [I18N.keystoneConnectionStepDescription2]:
    '"اختر "محفظة حق" أو "محفظة الحق".',
  [I18N.keystoneConnectionStepDescription3]:
    '"انقر فوق الزر ثلاثي النقاط, ثم انقر فوق "Connect Software Wallet" لمسح رمز الاستجابة السريعة المعروض على جهاز Keystone.',
  [I18N.keystoneCameraPermissionOpenSettings]: 'فتح الإعدادات',
  [I18N.keystoneCameraPermissionDeniedTitle]: 'لا يمكن الوصول إلى الكاميرا',
  [I18N.keystoneCameraPermissionDeniedDescription]:
    '"لا يستطيع التطبيق الوصول إلى الكاميرا الخاصة بك." يرجى الانتقال إلى إعدادات هاتفك والسماح للتطبيق باستخدام الكاميرا.وبدون ذلك, لن نتمكن من مسح رمز QR ضوئيًا على جهاز Keystone الخاص بك.',
  [I18N.keystoneCameraPermissionRequestTitle]: 'السماح باستخدام الكاميرا',
  [I18N.keystoneCameraPermissionRequestDescription]:
    'يستخدم التطبيق الكاميرا لمسح رمز الاستجابة السريعة الموجود على جهاز Keystone الخاص بك',
  [I18N.verifyCloudProblemsTitle]: 'يوجد خطأ في وحدة التخزين السحابية لديك',
  [I18N.verifyCloudProblemsNoReadError]: 'لا يمكن قراءة البيانات',
  [I18N.verifyCloudProblemsNoWriteError]: 'لا يمكن كتابة البيانات',
  [I18N.verifyCloudProblemsRestartPhone]:
    'عفوًا! هناك مشكلة صغيرة في خدمات Google. يرجى إيقاف تشغيل هاتفك ثم تشغيله مرة أخرى. وبعد ذلك, تحقق مما إذا كانت هناك أية تحديثات لنظامك.',
  [I18N.sssLimitReachedTitle]: 'الحد الأقصى لعدد\nالطلبات',
  [I18N.sssLimitReachedDescription]:
    'عذرًا, ولكن يبدو أن هناك مشكلة في حساب Apple/Google الخاص بك. لقد وصلت إلى الحد الأقصى لعدد الطلبات, لذا يرجى الانتظار لمدة دقيقة وإعادة الطلب',
  [I18N.sssLimitReachedButton]: 'إغلاق',
  [I18N.sssReplaceAccountTitle]: 'هل تريد استبدال حسابك؟',
  [I18N.sssReplaceAccountDescription1]:
    'الحساب مرتبط حاليًا بمعرف {{provider}} الخاص بك',
  [I18N.sssReplaceAccountDescription2]:
    ' ستفقد ولن تتمكن من الوصول إلى الأصول الموجودة في هذا الحساب.',
  [I18N.sssReplaceAccountButton]: 'تأكيد المحو',
  [I18N.signupImportantInfoTitle]: 'معلومات مهمة',
  [I18N.signupImportantInfoSecondaryButton]: 'اقرأ المزيد',
  [I18N.signupImportantInfoPrimaryButton]: 'متابعة',
  [I18N.signupImportantInfoDesc1]:
    '**سيتم تقسيم العبارة التذكيرية الخاصة بك إلى ثلاثة أجزاء, ** مخزنة على جهازك المحلي, وفي وحدة تخزين سحابية من اختيارك, وعلى السلسلة. أنت وحدك من يستطيع الوصول إلى هذه الأجزاء, مما يجعلها آمنة للغاية.',
  [I18N.signupImportantInfoDesc2]:
    'لاستخدام العبارة التذكيرية الخاصة بك, تحتاج فقط إلى اثنين من هذه الأجزاء الثلاثة. **لا يستطيع أي شخص آخر الوصول إلى هذه الأجزاء من العبارة التذكيرية الخاصة بك.**',
  [I18N.signupImportantInfoDesc3]:
    '**إذا فقدت هاتفك,** عن طريق الخطأ **احذف محفظة HAQQ,** أو **نسيت رقم التعريف الشخصي (PIN).** لا داعي للقلق! يمكنك استرداد محفظتك من خلال عبارة الأمان الخاصة بك باستخدام التخزين السحابي وتسجيل الدخول عبر مواقع التواصل الاجتماعي.',
  [I18N.signupImportantInfoDesc4]:
    '**إذا قمت في أي وقت بإزالة أي جزء من العبارة التذكيرية** المخزنة على وحدة التخزين السحابية الخاصة بك, فسيقوم التطبيق بإعلامك والتأكد من إصلاحها.',
  [I18N.signupImportantInfoDesc5]:
    'من المهم الحفاظ على أمان تفاصيل تسجيل الدخول الخاصة بك إلى Google أو Apple. إذا فقدتها وفقد هاتفك, فلن تتمكن من استعادة محفظتك باستخدام تسجيل الدخول إلى الوسائط الاجتماعية.',
  [I18N.erase]: 'مسح',
  [I18N.keystoneQrStep1]: 'مسح QR باستخدام Keystone الخاص بك',
  [I18N.keystoneQrStep2]:
    'بعد التوقيع باستخدام Keystone, اضغط على Get Signature',
  [I18N.keystoneQrGetSignature]: 'الحصول على التوقيع',
  [I18N.keystoneQrClose]: 'إغلاق',
  [I18N.customProviderEmail]: 'أدخل البريد الإلكتروني',
  [I18N.customProviderEmailPlaceholder]: 'some name@haqq',
  [I18N.customProviderEmailSubmit]: 'إرسال',
  [I18N.customProviderEmailCancel]: 'إلغاء',
  [I18N.createOrImportWallet]: 'يجب أن يكون لديك محفظة واحدة على الأقل!',
  [I18N.transactionRaffleRewardTitle]: 'مكافأة السحب',
  [I18N.transactioStakingRewardTitle]: 'مكافأة المكافأة',
  [I18N.transactionDelegationTitle]: 'المفوض',
  [I18N.transactionUndelegationTitle]: 'إلغاء التفويض',
  [I18N.transactionRedelegationTitle]: 'إعادة التفويض',
  [I18N.pinErrorModalClose]: 'إغلاق',
  [I18N.pinErrorModalTitle]: 'مشكلة في تحديث رمز PIN',
  [I18N.pinErrorModalDescription]:
    'لقد حاولنا تحديث الرمز السري, ولكن لسوء الحظ حدث خطأ أثناء التحديث. يرجى استخدام الرقم السري القديم',
  [I18N.recoveryPinTitle]: 'رقم التعريف الشخصي للاسترداد',
  [I18N.recoveryPinPlaceholder]: 'دبوسك القديم',
  [I18N.recoveryPinButton]: 'الاسترداد',
  [I18N.pinErrorModalRecoveryFail]: 'فشل رقم التعريف الشخصي للاسترداد',
  [I18N.recoveryPinSuccess]: 'تم استرداد رمز PIN الخاص بك بنجاح',
  [I18N.recoveryPinNoNeedRecovery]: 'لا حاجة لاستعادة رمز PIN',
  [I18N.recoveryPinSamePin]:
    'لا يمكن أن يكون دبوس الاسترداد هو نفس الدبوس الحالي',
  [I18N.transactionInfoFunctionValue]: 'مبلغ الرمز المميز',
  [I18N.recoveryPinDescription]:
    'إذا كانت لديك مشاكل في تغيير رمز PIN أو حصلت على خطأ "كلمة المرور غير صحيحة", فيمكنك في هذه الشاشة استعادة الوصول إلى المحافظ عن طريق إدخال الرقم السري الذي تريد التغيير إليه.',
  [I18N.isUsed]: 'مستخدم',
  [I18N.walletConnectConnectionEstablished]: 'تم إنشاء خادم اتصال المحفظة',
  [I18N.walletConnectConnectionLost]: 'تم فقدان خادم اتصال المحفظة',
  [I18N.walletConnectErrorClose]: 'إغلاق',
  [I18N.walletConnectErrorTitle]: 'خطأ في WalletConnect',
  [I18N.walletConnectInvalidUri]: 'URI غير صالح لـWalletConnect',
  [I18N.feeCalculatingRpcErrorTitle]: 'هناك خطأ ما',
  [I18N.feeCalculatingRpcErrorDescription]: 'فشل طلب تقدير الغاز',
  [I18N.feeCalculatingRpcErrorClose]: 'حاول ثانية',
  [I18N.swapWidgetTitle]: 'تجد محفظة حق أفضل سعر لمبادلة الرمز المميز الخاص بك',
  [I18N.swapWidgetDescription]: 'مبادلة الرموز',
  [I18N.jsonRpcSignBlidSignWarning]:
    "من أجل أمانك، تم تعطيل توقيع سلسلة الهكس افتراضيًا. يمكن تشفير المعاملات الخبيثة بشكل محتمل ضمن سلاسل الهكس. ومع ذلك، إذا كنت ترغب في تمكين توقيع الرسائل الهكس، يمكنك فعل ذلك في الإعدادات عن طريق تبديل 'توقيع الرسائل الهكس العمياء'. يرجى المتابعة بحذر، حيث يمكن أن يعرض هذا محفظتك لمخاطر محتملة.",
  [I18N.jsonRpcSignPhihsingWarning]:
    'نأسف لإبلاغك بأنه تم اكتشاف معاملة خبيثة ضمن الرسالة التي حاولت توقيعها. كإجراء احترازي، تم تعطيل توقيع الرسائل لحماية أموالك وبياناتك. يرجى مراجعة محتويات الرسالة والتأكد من سلامتها قبل محاولة التوقيع مرة أخرى. إذا كنت تعتقد أن هذا خطأ، يرجى الاتصال بفريق الدعم لدينا على الفور للمزيد من المساعدة.',
  [I18N.jsonRpcSignBlidGoToSettings]: 'الانتقال إلى إعدادات الأمان',
  [I18N.settingsSecurityHexBlindSign]: 'تمكين التوقيع الأعمى',
  [I18N.jsonRpcSignParsedMsg]: 'تم التحليل:',
  [I18N.settingsSecurityHexBlindSignDescription]:
    'تمكين التوقيع الأعمى لرسائل الهكس',
};
