import {ThemeColorsType, ThemeDictionaryType} from '@app/types';
import {
  DARK_BG_1,
  DARK_BG_10,
  DARK_BG_2,
  DARK_BG_3,
  DARK_BG_4,
  DARK_BG_5,
  DARK_BG_6,
  DARK_BG_7,
  DARK_BG_8,
  DARK_BG_9,
  DARK_GRAPHIC_BASE_1,
  DARK_GRAPHIC_BASE_2,
  DARK_GRAPHIC_BASE_3,
  DARK_GRAPHIC_BLUE_1,
  DARK_GRAPHIC_GREEN_1,
  DARK_GRAPHIC_GREEN_2,
  DARK_GRAPHIC_RED_1,
  DARK_GRAPHIC_SECOND_1,
  DARK_GRAPHIC_SECOND_2,
  DARK_GRAPHIC_SECOND_3,
  DARK_GRAPHIC_SECOND_4,
  DARK_TEXT_BASE_1,
  DARK_TEXT_BASE_2,
  DARK_TEXT_BASE_3,
  DARK_TEXT_BLUE_1,
  DARK_TEXT_GREEN_1,
  DARK_TEXT_RED_1,
  DARK_TEXT_SECOND_1,
  DARK_TEXT_SECOND_2,
  DARK_TEXT_YELLOW_1,
  LIGHT_BG_1,
  LIGHT_BG_10,
  LIGHT_BG_2,
  LIGHT_BG_3,
  LIGHT_BG_4,
  LIGHT_BG_5,
  LIGHT_BG_6,
  LIGHT_BG_7,
  LIGHT_BG_8,
  LIGHT_BG_9,
  LIGHT_GRAPHIC_BASE_1,
  LIGHT_GRAPHIC_BASE_2,
  LIGHT_GRAPHIC_BASE_3,
  LIGHT_GRAPHIC_BLUE_1,
  LIGHT_GRAPHIC_GREEN_1,
  LIGHT_GRAPHIC_GREEN_2,
  LIGHT_GRAPHIC_RED_1,
  LIGHT_GRAPHIC_SECOND_1,
  LIGHT_GRAPHIC_SECOND_2,
  LIGHT_GRAPHIC_SECOND_3,
  LIGHT_GRAPHIC_SECOND_4,
  LIGHT_TEXT_BASE_1,
  LIGHT_TEXT_BASE_2,
  LIGHT_TEXT_BASE_3,
  LIGHT_TEXT_BLUE_1,
  LIGHT_TEXT_GREEN_1,
  LIGHT_TEXT_RED_1,
  LIGHT_TEXT_SECOND_1,
  LIGHT_TEXT_SECOND_2,
  LIGHT_TEXT_YELLOW_1,
  TRANSPARENT,
} from '@app/variables/common';

export const LIGHT_THEME: ThemeColorsType = {
  transparent: TRANSPARENT,
  textBase1: LIGHT_TEXT_BASE_1,
  textBase2: LIGHT_TEXT_BASE_2,
  textBase3: LIGHT_TEXT_BASE_3,
  textSecond1: LIGHT_TEXT_SECOND_1,
  textSecond2: LIGHT_TEXT_SECOND_2,
  textGreen1: LIGHT_TEXT_GREEN_1,
  textRed1: LIGHT_TEXT_RED_1,
  textYellow1: LIGHT_TEXT_YELLOW_1,
  textBlue1: LIGHT_TEXT_BLUE_1,
  bg1: LIGHT_BG_1,
  bg2: LIGHT_BG_2,
  bg3: LIGHT_BG_3,
  bg4: LIGHT_BG_4,
  bg5: LIGHT_BG_5,
  bg6: LIGHT_BG_6,
  bg7: LIGHT_BG_7,
  bg8: LIGHT_BG_8,
  bg9: LIGHT_BG_9,
  bg10: LIGHT_BG_10,
  graphicBase1: LIGHT_GRAPHIC_BASE_1,
  graphicBase2: LIGHT_GRAPHIC_BASE_2,
  graphicBase3: LIGHT_GRAPHIC_BASE_3,
  graphicRed1: LIGHT_GRAPHIC_RED_1,
  graphicGreen1: LIGHT_GRAPHIC_GREEN_1,
  graphicGreen2: LIGHT_GRAPHIC_GREEN_2,
  graphicSecond1: LIGHT_GRAPHIC_SECOND_1,
  graphicSecond2: LIGHT_GRAPHIC_SECOND_2,
  graphicSecond3: LIGHT_GRAPHIC_SECOND_3,
  graphicSecond4: LIGHT_GRAPHIC_SECOND_4,
  graphicBlue1: LIGHT_GRAPHIC_BLUE_1,
};

export const DARK_THEME: ThemeColorsType = {
  transparent: TRANSPARENT,
  textBase1: DARK_TEXT_BASE_1,
  textBase2: DARK_TEXT_BASE_2,
  textBase3: DARK_TEXT_BASE_3,
  textSecond1: DARK_TEXT_SECOND_1,
  textSecond2: DARK_TEXT_SECOND_2,
  textGreen1: DARK_TEXT_GREEN_1,
  textRed1: DARK_TEXT_RED_1,
  textYellow1: DARK_TEXT_YELLOW_1,
  textBlue1: DARK_TEXT_BLUE_1,
  bg1: DARK_BG_1,
  bg2: DARK_BG_2,
  bg3: DARK_BG_3,
  bg4: DARK_BG_4,
  bg5: DARK_BG_5,
  bg6: DARK_BG_6,
  bg7: DARK_BG_7,
  bg8: DARK_BG_8,
  bg9: DARK_BG_9,
  bg10: DARK_BG_10,
  graphicBase1: DARK_GRAPHIC_BASE_1,
  graphicBase2: DARK_GRAPHIC_BASE_2,
  graphicBase3: DARK_GRAPHIC_BASE_3,
  graphicRed1: DARK_GRAPHIC_RED_1,
  graphicGreen1: DARK_GRAPHIC_GREEN_1,
  graphicGreen2: DARK_GRAPHIC_GREEN_2,
  graphicSecond1: DARK_GRAPHIC_SECOND_1,
  graphicSecond2: DARK_GRAPHIC_SECOND_2,
  graphicSecond3: DARK_GRAPHIC_SECOND_3,
  graphicSecond4: DARK_GRAPHIC_SECOND_4,
  graphicBlue1: DARK_GRAPHIC_BLUE_1,
};

export enum Color {
  transparent = 'transparent',
  textBase1 = 'textBase1',
  textBase2 = 'textBase2',
  textBase3 = 'textBase3',
  textSecond1 = 'textSecond1',
  textSecond2 = 'textSecond2',
  textGreen1 = 'textGreen1',
  textRed1 = 'textRed1',
  textYellow1 = 'textYellow1',
  textBlue1 = 'textBlue1',
  bg1 = 'bg1',
  bg2 = 'bg2',
  bg3 = 'bg3',
  bg4 = 'bg4',
  bg5 = 'bg5',
  bg6 = 'bg6',
  bg7 = 'bg7',
  bg8 = 'bg8',
  bg9 = 'bg9',
  bg10 = 'bg10',
  graphicBase1 = 'graphicBase1',
  graphicBase2 = 'graphicBase2',
  graphicBase3 = 'graphicBase3',
  graphicRed1 = 'graphicRed1',
  graphicBlue1 = 'graphicBlue1',
  graphicGreen1 = 'graphicGreen1',
  graphicGreen2 = 'graphicGreen2',
  graphicSecond1 = 'graphicSecond1',
  graphicSecond2 = 'graphicSecond2',
  graphicSecond3 = 'graphicSecond3',
  graphicSecond4 = 'graphicSecond4',
}

export const SupportedThemes = ['light', 'dark'] as const;
export type ThemeNameType = typeof SupportedThemes[number];
export const ThemeDictionary: ThemeDictionaryType = {
  light: LIGHT_THEME,
  dark: DARK_THEME,
};
