declare module '@env' {
  export const PROVIDER_NETWORK: string;
  export const PROVIDER_WS_NETWORK: string;
  export const PROVIDER_CHAIN_ID: string;
  export const SENTRY_DSN: string;
  export const NETWORK_EXPLORER: string;
  export const PATTERNS_SOURCE: string;
  export const ENVIRONMENT: string;
  export const IS_DEVELOPMENT: string;
  export const PUSH_NOTIFICATIONS: string;
  export const PROVIDER_BASE_PACKAGE: string;
  export const WALLET_CONNECT_PROJECT_ID: string;
  export const WALLET_CONNECT_RELAY_URL: string;
  export const WEB3AUTH_CLIENT_ID: string;
  export const WEB3AUTH_AUTH0_CLIENT_ID: string;
  export const WEB3AUTH_AUTH0_VERIFIER: string;
  export const WEB3AUTH_AUTH0_DOMAIN: string;
  export const HCAPTCHA_SITE_KEY: string;
}
