declare module '@env' {
  export const PROVIDER_NETWORK: string;
  export const PROVIDER_WS_NETWORK: string;
  export const PROVIDER_CHAIN_ID: string;
  export const SENTRY_DSN: string;
  export const NETWORK_EXPLORER: string;
  export const PATTERNS_SOURCE: string;
  export const ENVIRONMENT: string;
  export const IS_DEVELOPMENT: string;
  export const PUSH_NOTIFICATIONS_URL: string;
  export const PROVIDER_BASE_PACKAGE: string;
  export const WALLET_CONNECT_PROJECT_ID: string;
  export const WALLET_CONNECT_RELAY_URL: string;
  export const WEB3AUTH_CLIENT_ID: string;
  export const HCAPTCHA_SITE_KEY: string;
  export const GOOGLE_SIGNIN_WEB_CLIENT_ID: string;
  export const CUSTOM_JWT_TOKEN: string;
  export const MPC_STORE_URL: string;
  export const MPC_NETWORK: string;
  export const MPC_GOOGLE_IOS: string;
  export const MPC_GOOGLE_ANDROID: string;
  export const MPC_APPLE: string;
  export const MPC_CUSTOM: string;
  export const METADATA_URL: string;
  export const GENERATE_SHARES_URL: string;
  export const IS_MPC_ENABLED: string;
  export const AIRDROP_TESTEDGE2_URL: string;
  export const AIRDROP_MAINNET_URL: string;
}
