# Overview
# This GitHub Action runs for every merged PR.

name: Merge Queue Action [TRIGGER]

on:
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
      - name: Show self-hosted machine infomation
        run: uname -a

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup NodeJS@18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install packages
        run: yarn install

      - name: Run linters
        run: |
          yarn lint
          yarn typescript:check
          yarn prettier:check

      - name: Build iOS JS Bundle
        run: yarn react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ./index.ios.bundle