name: Check PR labels
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled

jobs:
  label:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check-labels.outputs.status }}
    steps:
      - name: Check labels
        id: check-labels
        uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 1
          labels: "no-qa, need-qa"
          exit_type: success
  verify:
    runs-on: ubuntu-latest
    needs: label
    steps:
      - name: Comment PR
        if: needs.label.outputs.status == 'failure'
        uses: thollander/actions-comment-pull-request@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            Requires exactly 1 of: no-qa, need-qa labels

      - run: echo FAILURE && exit 1
        if: needs.label.outputs.status == 'failure'

      - run: echo SUCCESS
        if: needs.label.outputs.status == 'success'
