name: Check PR title
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited

jobs:
  lint:
    runs-on: ubuntu-cpu16-ram64
    steps:
      - uses: aslafy-z/conventional-pr-title-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
